## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../../Modules")

from utils import *

enc = 'utf-8'
dec = 'greek8'
random.seed(0)

In [2]:
NUTS0 = 'GR'
NUTS2 = 'Thrace'

In [3]:
nuts2_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Grid_NUTS3.csv', encoding = enc)
nuts2_grid.head()

  NUTS2_ID                  NUTS2_NAME NUTS3_ID NUTS3_NAME         x         y
0     EL51  ανατολικη μακεδονια, θρακη    EL514      δραμα  24.02794  41.27306
1     EL51  ανατολικη μακεδονια, θρακη    EL514      δραμα  24.26588  41.52459
2     EL51  ανατολικη μακεδονια, θρακη    EL514      δραμα  24.31347  41.09339
3     EL51  ανατολικη μακεδονια, θρακη    EL514      δραμα  24.31347  41.12933
4     EL51  ανατολικη μακεδονια, θρακη    EL514      δραμα  24.31347  41.16526

In [4]:
## start and end date is defined from available epidemiological file

In [5]:
start = start_dt = date(2024, 9, 2)
end = end_dt = date(2024, 10, 1)
delta = timedelta(days=1)

In [6]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [7]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2024-09-02 and 2024-10-01
['2024-09-02', '2024-09-03', '2024-09-04', '2024-09-05', '2024-09-06', '2024-09-07', '2024-09-08', '2024-09-09', '2024-09-10', '2024-09-11', '2024-09-12', '2024-09-13', '2024-09-14', '2024-09-15', '2024-09-16', '2024-09-17', '2024-09-18', '2024-09-19', '2024-09-20', '2024-09-21', '2024-09-22', '2024-09-23', '2024-09-24', '2024-09-25', '2024-09-26', '2024-09-27', '2024-09-28', '2024-09-29', '2024-09-30', '2024-10-01']

In [8]:
len(dates)

30

In [9]:
print(f'Total Rows: {len(dates) * len(nuts2_grid)}')

Total Rows: 19830

In [10]:
nuts2_timeline = pd.DataFrame()

In [11]:
data = []
for index, row in nuts2_grid.iterrows():
    for date in dates:
        data.append({'NUTS2_ID': row['NUTS2_ID'], 
                     'NUTS2_NAME': row['NUTS2_NAME'],
                     'NUTS3_ID': row['NUTS3_ID'], 
                     'NUTS3_NAME': row['NUTS3_NAME'], 
                     'x': row['x'], 
                     'y': row['y'], 
                     'dt_placement': date})

nuts2_timeline = pd.DataFrame(data)

In [12]:
nuts2_timeline

,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,x,y,dt_placement
0,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,24.02794,41.27306,2024-09-02
1,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,24.02794,41.27306,2024-09-03
2,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,24.02794,41.27306,2024-09-04
3,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,24.02794,41.27306,2024-09-05
4,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,24.02794,41.27306,2024-09-06
...,...,...,...,...,...,...,...
19825,EL51,"ανατολικη μακεδονια, θρακη",EL513,ροδοπη,25.45025,41.09130,2024-09-27
19826,EL51,"ανατολικη μακεδονια, θρακη",EL513,ροδοπη,25.45025,41.09130,2024-09-28
19827,EL51,"ανατολικη μακεδονια, θρακη",EL513,ροδοπη,25.45025,41.09130,2024-09-29
19828,EL51,"ανατολικη μακεδονια, θρακη",EL513,ροδοπη,25.45025,41.09130,2024-09-30
19829,EL51,"ανατολικη μακεδονια, θρακη",EL513,ροδοπη,25.45025,41.09130,2024-10-01

In [13]:
nuts2_timeline['dt_placement'] = pd.to_datetime(nuts2_timeline['dt_placement'])

In [14]:
nuts2_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19830 entries, 0 to 19829
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   NUTS2_ID      19830 non-null  object
 1   NUTS2_NAME    19830 non-null  object
 2   NUTS3_ID      19830 non-null  object
 3   NUTS3_NAME    19830 non-null  object
 4   x             19830 non-null  float64
 5   y             19830 non-null  float64
 6   dt_placement  19830 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(4)
memory usage: 1.1+ MB

In [15]:
nuts2_timeline.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_NUTS3_2024.csv', index = False)