In [14]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

enc = 'utf-8'

In [15]:
base_folder = 'E:/Drive/NOA/MBD-Prediction/NUTS3 Level/Greece/data/'

In [16]:
NUTS2 = 'Thrace'
YEAR = '2024'

In [17]:
data = pd.read_csv(f'{base_folder}/{NUTS2}/GR_{NUTS2}_Timeline_NUTS3_{YEAR}_filled_mean.csv', encoding=enc)

In [18]:
try:
    data.drop(columns=['Unnamed: 0'], inplace=True)
except Exception:
    print("No column named \'Unnamed: 0\'")

In [19]:
data['dt_placement'] = pd.to_datetime(data['dt_placement'])

# Extract year, month, and day from the 'date' column
data['year'] = data['dt_placement'].dt.year
data['month'] = data['dt_placement'].dt.month
data['day'] = data['dt_placement'].dt.day

In [20]:
data

,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,x,y,dt_placement,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean
0,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,23.69482,41.34493,2024-01-01,2024,1,0.284574,-0.14387,-0.272169,0.14387,0.270964,-0.054752,-0.207973,0.054752,0.024776,0.054316,0.051266,0.054316,13998.0,13676.0,0.001530,1,13917.050069,13619.718979,14162.914322,13779.140106,14311.732634,13880.081948,14751.354397,14127.758487
1,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,23.69482,41.34493,2024-01-02,2024,1,0.284574,-0.14387,-0.272169,0.14387,0.270964,-0.054752,-0.207973,0.054752,0.024776,0.054316,0.051266,0.054316,13998.0,13755.0,0.310446,2,13917.050069,13619.718979,14162.914322,13779.140106,14311.732634,13880.081948,14751.354397,14127.758487
2,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,23.69482,41.34493,2024-01-03,2024,1,0.284574,-0.14387,-0.272169,0.14387,0.270964,-0.054752,-0.207973,0.054752,0.024776,0.054316,0.051266,0.054316,13998.0,13755.0,0.512597,3,13917.050069,13619.718979,14162.914322,13779.140106,14311.732634,13880.081948,14751.354397,14127.758487
3,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,23.69482,41.34493,2024-01-04,2024,1,0.284574,-0.14387,-0.272169,0.14387,0.270964,-0.054752,-0.207973,0.054752,0.024776,0.054316,0.051266,0.054316,13756.0,13905.0,0.000000,4,13917.050069,13619.718979,14162.914322,13779.140106,14311.732634,13880.081948,14751.354397,14127.758487
4,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,23.69482,41.34493,2024-01-05,2024,1,0.284574,-0.14387,-0.272169,0.14387,0.270964,-0.054752,-0.207973,0.054752,0.024776,0.054316,0.051266,0.054316,13756.0,13905.0,0.000000,5,13917.050069,13619.718979,14162.914322,13779.140106,14311.732634,13880.081948,14751.354397,14127.758487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141449,EL51,"ανατολικη μακεδονια, θρακη",EL513,ροδοπη,25.49776,40.91163,2024-08-01,2024,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15630.0,14755.0,NaN,1,14099.633715,13711.818158,14306.535039,13899.578420,14459.404266,13932.547867,14842.184409,14233.125806
141450,EL51,"ανατολικη μακεδονια, θρακη",EL513,ροδοπη,25.45025,41.23503,2024-08-01,2024,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15203.0,14689.0,NaN,1,14099.633715,13711.818158,14306.535039,13899.578420,14459.404266,13932.547867,14842.184409,14233.125806
141451,EL51,"ανατολικη μακεδονια, θρακη",EL513,ροδοπη,25.45025,41.19910,2024-08-01,2024,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15395.0,14735.0,NaN,1,14099.633715,13711.818158,14306.535039,13899.578420,14459.404266,13932.547867,14842.184409,14233.125806
141452,EL51,"ανατολικη μακεδονια, θρακη",EL513,ροδοπη,25.49776,41.19910,2024-08-01,2024,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15424.0,14750.0,NaN,1,14099.633715,13711.818158,14306.535039,13899.578420,14459.404266,13932.547867,14842.184409,14233.125806
141453,EL51,"ανατολικη μακεδονια, θρακη",EL513,ροδοπη,25.45025,41.09130,2024-08-01,2024,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15741.0,14677.0,NaN,1,14099.633715,13711.818158,14306.535039,13899.578420,14459.404266,13932.547867,14842.184409,14233.125806

In [21]:
dataset_list = []
groups = data.groupby(['x', 'y', 'year'])

In [22]:
num_of_groups = len(groups)

In [23]:
c = 0

for group, frame in groups:
    print(f"Iteration: {c}/{num_of_groups}", end='\r')
    temp_df = frame.copy()
    temp_df.reset_index(drop=True, inplace=True)
    temp_df['acc_rainfall_1week'] = temp_df['rainfall'].rolling(window=7, min_periods=0).sum()
    temp_df['acc_rainfall_2week'] = temp_df['rainfall'].rolling(window=14, min_periods=0).sum()
    temp_df['acc_rainfall_month'] = temp_df['rainfall'].rolling(window=30, min_periods=0).sum()
    temp_df['acc_rainfall_jan'] = temp_df['dt_placement'].apply(lambda x: temp_df.loc[temp_df['dt_placement'] <= x, 'rainfall'].sum())
    dataset_list.append(temp_df)
    c = c + 1

In [24]:
dataset = pd.concat(dataset_list, ignore_index=True)
dataset.reset_index(drop=True, inplace=True)

In [25]:
dataset

,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,x,y,dt_placement,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan
0,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,23.69482,41.34493,2024-01-01,2024,1,0.284574,-0.14387,-0.272169,0.14387,0.270964,-0.054752,-0.207973,0.054752,0.024776,0.054316,0.051266,0.054316,13998.0,13676.0,0.001530,1,13917.050069,13619.718979,14162.914322,13779.140106,14311.732634,13880.081948,14751.354397,14127.758487,0.001530,0.001530,0.001530,0.001530
1,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,23.69482,41.34493,2024-01-02,2024,1,0.284574,-0.14387,-0.272169,0.14387,0.270964,-0.054752,-0.207973,0.054752,0.024776,0.054316,0.051266,0.054316,13998.0,13755.0,0.310446,2,13917.050069,13619.718979,14162.914322,13779.140106,14311.732634,13880.081948,14751.354397,14127.758487,0.311976,0.311976,0.311976,0.311976
2,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,23.69482,41.34493,2024-01-03,2024,1,0.284574,-0.14387,-0.272169,0.14387,0.270964,-0.054752,-0.207973,0.054752,0.024776,0.054316,0.051266,0.054316,13998.0,13755.0,0.512597,3,13917.050069,13619.718979,14162.914322,13779.140106,14311.732634,13880.081948,14751.354397,14127.758487,0.824574,0.824574,0.824574,0.824574
3,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,23.69482,41.34493,2024-01-04,2024,1,0.284574,-0.14387,-0.272169,0.14387,0.270964,-0.054752,-0.207973,0.054752,0.024776,0.054316,0.051266,0.054316,13756.0,13905.0,0.000000,4,13917.050069,13619.718979,14162.914322,13779.140106,14311.732634,13880.081948,14751.354397,14127.758487,0.824574,0.824574,0.824574,0.824574
4,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,23.69482,41.34493,2024-01-05,2024,1,0.284574,-0.14387,-0.272169,0.14387,0.270964,-0.054752,-0.207973,0.054752,0.024776,0.054316,0.051266,0.054316,13756.0,13905.0,0.000000,5,13917.050069,13619.718979,14162.914322,13779.140106,14311.732634,13880.081948,14751.354397,14127.758487,0.824574,0.824574,0.824574,0.824574
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141449,EL51,"ανατολικη μακεδονια, θρακη",EL511,εβρος,26.60558,41.38034,2024-07-28,2024,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15707.0,14797.0,NaN,28,14086.249032,13726.772419,14341.048276,13920.649138,14444.408548,13928.651290,14865.151500,14220.632667,0.000000,0.000000,0.000000,160.586929
141450,EL51,"ανατολικη μακεδονια, θρακη",EL511,εβρος,26.60558,41.38034,2024-07-29,2024,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15625.0,14870.0,NaN,29,14086.249032,13726.772419,14341.048276,13920.649138,14444.408548,13928.651290,14865.151500,14220.632667,0.000000,0.000000,0.000000,160.586929
141451,EL51,"ανατολικη μακεδονια, θρακη",EL511,εβρος,26.60558,41.38034,2024-07-30,2024,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15653.0,14780.0,NaN,30,14086.249032,13726.772419,14341.048276,13920.649138,14444.408548,13928.651290,14865.151500,14220.632667,0.000000,0.000000,0.000000,160.586929
141452,EL51,"ανατολικη μακεδονια, θρακη",EL511,εβρος,26.60558,41.38034,2024-07-31,2024,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15530.0,14621.0,NaN,31,14086.249032,13726.772419,14341.048276,13920.649138,14444.408548,13928.651290,14865.151500,14220.632667,0.000000,0.000000,0.000000,160.586929
141453,EL51,"ανατολικη μακεδονια, θρακη",EL511,εβρος,26.60558,41.38034,2024-08-01,2024,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15645.0,14790.0,NaN,1,14086.249032,13726.772419,14341.048276,13920.649138,14444.408548,13928.651290,14865.151500,14220.632667,0.000000,0.000000,0.000000,160.586929

In [26]:
dataset.to_csv(f'{base_folder}/{NUTS2}/GR_{NUTS2}_Timeline_NUTS3_{YEAR}_filled_mean_rain.csv', encoding='utf-8')