In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

enc = 'utf-8'

In [2]:
base_folder = 'E:/Drive/NOA/MBD-Prediction/NUTS3 - Level/Greece/data/'

In [3]:
NUTS2 = 'Thessaly'
YEAR = '2024'

In [4]:
data = pd.read_csv(f'{base_folder}/{NUTS2}/GR_{NUTS2}_Timeline_NUTS3_{YEAR}_filled_mean.csv', encoding=enc)

In [5]:
try:
    data.drop(columns=['Unnamed: 0'], inplace=True)
except Exception:
    print("No column named \'Unnamed: 0\'")

In [6]:
data['dt_placement'] = pd.to_datetime(data['dt_placement'])

# Extract year, month, and day from the 'date' column
data['year'] = data['dt_placement'].dt.year
data['month'] = data['dt_placement'].dt.month
data['day'] = data['dt_placement'].dt.day

In [7]:
data

,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,x,y,dt_placement,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean
0,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-01-01,2024,1,0.473835,0.142222,-0.420871,-0.142222,0.388692,0.274328,-0.303196,-0.274328,0.140335,0.143803,0.112971,0.143803,13814.0,13689.0,1.164514,1,14069.498986,13795.242950,14221.000651,13851.791043,14423.290830,13932.471495,14831.676478,14172.936101
1,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-01-02,2024,1,0.473835,0.142222,-0.420871,-0.142222,0.388692,0.274328,-0.303196,-0.274328,0.140335,0.143803,0.112971,0.143803,13814.0,13712.0,11.846938,2,14069.498986,13795.242950,14221.000651,13851.791043,14423.290830,13932.471495,14831.676478,14172.936101
2,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-01-03,2024,1,0.473835,0.142222,-0.420871,-0.142222,0.388692,0.274328,-0.303196,-0.274328,0.140335,0.143803,0.112971,0.143803,13814.0,13712.0,0.714449,3,14069.498986,13795.242950,14221.000651,13851.791043,14423.290830,13932.471495,14831.676478,14172.936101
3,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-01-04,2024,1,0.473835,0.142222,-0.420871,-0.142222,0.388692,0.274328,-0.303196,-0.274328,0.140335,0.143803,0.112971,0.143803,13814.0,13834.0,0.000000,4,14069.498986,13795.242950,14221.000651,13851.791043,14423.290830,13932.471495,14831.676478,14172.936101
4,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-01-05,2024,1,0.473835,0.142222,-0.420871,-0.142222,0.388692,0.274328,-0.303196,-0.274328,0.140335,0.143803,0.112971,0.143803,13854.0,13678.0,0.250432,5,14069.498986,13795.242950,14221.000651,13851.791043,14423.290830,13932.471495,14831.676478,14172.936101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84663,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",22.74624,39.31112,2024-05-01,2024,5,0.657875,0.377295,-0.567324,-0.377295,0.533775,0.229863,-0.484205,-0.229863,0.091889,0.106971,0.061969,0.106971,NaN,NaN,NaN,1,14164.182907,13935.828733,14288.283327,13976.150729,14442.140007,14031.694047,14802.364536,14257.066804
84664,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",22.74624,39.27518,2024-05-01,2024,5,0.377570,0.176377,-0.317248,-0.176377,0.412067,0.206542,-0.339813,-0.206542,0.041501,0.030382,0.038669,0.030382,NaN,NaN,NaN,1,14164.182907,13935.828733,14288.283327,13976.150729,14442.140007,14031.694047,14802.364536,14257.066804
84665,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",22.74624,39.23925,2024-05-01,2024,5,0.318741,0.115418,-0.321000,-0.115418,0.357992,0.105538,-0.354827,-0.105538,0.111367,0.083026,0.085742,0.083026,NaN,NaN,NaN,1,14164.182907,13935.828733,14288.283327,13976.150729,14442.140007,14031.694047,14802.364536,14257.066804
84666,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",22.74624,39.16738,2024-05-01,2024,5,0.377635,0.153777,-0.372142,-0.153777,0.344275,0.125509,-0.362614,-0.125509,0.035156,0.029671,0.018951,0.029671,NaN,NaN,NaN,1,14164.182907,13935.828733,14288.283327,13976.150729,14442.140007,14031.694047,14802.364536,14257.066804
84667,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2024-05-01,2024,5,0.613499,0.351106,-0.510581,-0.351106,0.619998,0.342725,-0.516247,-0.342725,0.022556,0.028363,0.010026,0.028363,NaN,NaN,NaN,1,14164.182907,13935.828733,14288.283327,13976.150729,14442.140007,14031.694047,14802.364536,14257.066804

In [8]:
dataset_list = []
groups = data.groupby(['x', 'y', 'year'])

In [9]:
num_of_groups = len(groups)

In [10]:
c = 0

for group, frame in groups:
    print(f"Iteration: {c}/{num_of_groups}", end='\r')
    temp_df = frame.copy()
    temp_df.reset_index(drop=True, inplace=True)
    temp_df['acc_rainfall_1week'] = temp_df['rainfall'].rolling(window=7, min_periods=0).sum()
    temp_df['acc_rainfall_2week'] = temp_df['rainfall'].rolling(window=14, min_periods=0).sum()
    temp_df['acc_rainfall_month'] = temp_df['rainfall'].rolling(window=30, min_periods=0).sum()
    temp_df['acc_rainfall_jan'] = temp_df['dt_placement'].apply(lambda x: temp_df.loc[temp_df['dt_placement'] <= x, 'rainfall'].sum())
    dataset_list.append(temp_df)
    c = c + 1

In [11]:
dataset = pd.concat(dataset_list, ignore_index=True)
dataset.reset_index(drop=True, inplace=True)

In [12]:
dataset

,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,x,y,dt_placement,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan
0,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-01-01,2024,1,0.473835,0.142222,-0.420871,-0.142222,0.388692,0.274328,-0.303196,-0.274328,0.140335,0.143803,0.112971,0.143803,13814.0,13689.0,1.164514,1,14069.498986,13795.242950,14221.000651,13851.791043,14423.290830,13932.471495,14831.676478,14172.936101,1.164514,1.164514,1.164514,1.164514
1,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-01-02,2024,1,0.473835,0.142222,-0.420871,-0.142222,0.388692,0.274328,-0.303196,-0.274328,0.140335,0.143803,0.112971,0.143803,13814.0,13712.0,11.846938,2,14069.498986,13795.242950,14221.000651,13851.791043,14423.290830,13932.471495,14831.676478,14172.936101,13.011452,13.011452,13.011452,13.011452
2,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-01-03,2024,1,0.473835,0.142222,-0.420871,-0.142222,0.388692,0.274328,-0.303196,-0.274328,0.140335,0.143803,0.112971,0.143803,13814.0,13712.0,0.714449,3,14069.498986,13795.242950,14221.000651,13851.791043,14423.290830,13932.471495,14831.676478,14172.936101,13.725901,13.725901,13.725901,13.725901
3,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-01-04,2024,1,0.473835,0.142222,-0.420871,-0.142222,0.388692,0.274328,-0.303196,-0.274328,0.140335,0.143803,0.112971,0.143803,13814.0,13834.0,0.000000,4,14069.498986,13795.242950,14221.000651,13851.791043,14423.290830,13932.471495,14831.676478,14172.936101,13.725901,13.725901,13.725901,13.725901
4,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-01-05,2024,1,0.473835,0.142222,-0.420871,-0.142222,0.388692,0.274328,-0.303196,-0.274328,0.140335,0.143803,0.112971,0.143803,13854.0,13678.0,0.250432,5,14069.498986,13795.242950,14221.000651,13851.791043,14423.290830,13932.471495,14831.676478,14172.936101,13.976333,13.976333,13.976333,13.976333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84663,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2024-04-27,2024,4,0.613499,0.351106,-0.510581,-0.351106,0.619998,0.342725,-0.516247,-0.342725,0.022556,0.028363,0.010026,0.028363,NaN,NaN,1.457747,27,14164.182907,13935.828733,14288.283327,13976.150729,14442.140007,14031.694047,14802.364536,14257.066804,28.044588,164.587026,165.833447,653.889144
84664,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2024-04-28,2024,4,0.613499,0.351106,-0.510581,-0.351106,0.619998,0.342725,-0.516247,-0.342725,0.022556,0.028363,0.010026,0.028363,NaN,NaN,0.000000,28,14164.182907,13935.828733,14288.283327,13976.150729,14442.140007,14031.694047,14802.364536,14257.066804,27.845099,164.346087,165.833447,653.889144
84665,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2024-04-29,2024,4,0.613499,0.351106,-0.510581,-0.351106,0.619998,0.342725,-0.516247,-0.342725,0.022556,0.028363,0.010026,0.028363,NaN,NaN,0.000000,29,14164.182907,13935.828733,14288.283327,13976.150729,14442.140007,14031.694047,14802.364536,14257.066804,2.410387,164.346087,165.833447,653.889144
84666,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2024-04-30,2024,4,0.613499,0.351106,-0.510581,-0.351106,0.619998,0.342725,-0.516247,-0.342725,0.022556,0.028363,0.010026,0.028363,NaN,NaN,NaN,30,14164.182907,13935.828733,14288.283327,13976.150729,14442.140007,14031.694047,14802.364536,14257.066804,2.260232,164.088007,165.833447,653.889144
84667,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2024-05-01,2024,5,0.613499,0.351106,-0.510581,-0.351106,0.619998,0.342725,-0.516247,-0.342725,0.022556,0.028363,0.010026,0.028363,NaN,NaN,NaN,1,14164.182907,13935.828733,14288.283327,13976.150729,14442.140007,14031.694047,14802.364536,14257.066804,2.260018,161.449158,165.637443,653.889144

In [13]:
dataset.to_csv(f'{base_folder}/{NUTS2}/GR_{NUTS2}_Timeline_NUTS3_{YEAR}_filled_mean_rain.csv', encoding='utf-8')