In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [3]:
data = pd.read_csv('GR_Timeline_2009-2022_filled_mean.csv', encoding='utf-8')

In [4]:
try:
    data.drop(columns=['Unnamed: 0'], inplace=True)
except Exception:
    print("No column named \'Unnamed: 0\'")

In [5]:
data['dt_placement'] = pd.to_datetime(data['dt_placement'])

# Extract year, month, and day from the 'date' column
data['year'] = data['dt_placement'].dt.year
data['month'] = data['dt_placement'].dt.month
data['day'] = data['dt_placement'].dt.day

In [6]:
data

,x,y,cell_code,dt_placement,NUTS1_ID,NUTS1_NAME,NUTS2_ID,NUTS2_NAME,NUTS3_ID,LAU1_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean
0,23.722470,38.078795,OU372,2009-01-01,EL3,αττικη,EL30,αττικη,EL305,αχαρνων,2.0,1.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14112.0,13780.0,0.000000,1,14272.870968,13947.709677,14304.428571,13893.321429,14593.612903,13974.096774,14909.800000,14193.633333
1,23.722470,38.078795,OU372,2009-01-02,EL3,αττικη,EL30,αττικη,EL305,αχαρνων,2.0,1.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14112.0,13780.0,2.866936,2,14272.870968,13947.709677,14304.428571,13893.321429,14593.612903,13974.096774,14909.800000,14193.633333
2,23.722470,38.078795,OU372,2009-01-03,EL3,αττικη,EL30,αττικη,EL305,αχαρνων,2.0,1.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14112.0,13780.0,13.926683,3,14272.870968,13947.709677,14304.428571,13893.321429,14593.612903,13974.096774,14909.800000,14193.633333
3,23.722470,38.078795,OU372,2009-01-04,EL3,αττικη,EL30,αττικη,EL305,αχαρνων,2.0,1.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14112.0,13780.0,2.439608,4,14272.870968,13947.709677,14304.428571,13893.321429,14593.612903,13974.096774,14909.800000,14193.633333
4,23.722470,38.078795,OU372,2009-01-05,EL3,αττικη,EL30,αττικη,EL305,αχαρνων,2.0,1.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14112.0,13780.0,10.252046,5,14272.870968,13947.709677,14304.428571,13893.321429,14593.612903,13974.096774,14909.800000,14193.633333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22522760,22.205622,38.561047,MR240,2022-12-27,EL6,κεντρικη ελλαδα,EL64,στερεα ελλαδα,EL645,δωριδος,3.0,3.0,1.0,2022,12,0.286783,0.262643,-0.072022,-0.262643,0.355929,0.180265,-0.212274,-0.180265,0.05997,0.098978,0.11779,0.098978,14211.0,13959.0,0.000000,27,13975.225806,13688.451613,14069.714286,13731.035714,14104.580645,13616.322581,14506.133333,13992.200000
22522761,22.205622,38.561047,MR240,2022-12-28,EL6,κεντρικη ελλαδα,EL64,στερεα ελλαδα,EL645,δωριδος,3.0,3.0,1.0,2022,12,0.286783,0.262643,-0.072022,-0.262643,0.355929,0.180265,-0.212274,-0.180265,0.05997,0.098978,0.11779,0.098978,14139.0,13975.0,0.000000,28,13975.225806,13688.451613,14069.714286,13731.035714,14104.580645,13616.322581,14506.133333,13992.200000
22522762,22.205622,38.561047,MR240,2022-12-29,EL6,κεντρικη ελλαδα,EL64,στερεα ελλαδα,EL645,δωριδος,3.0,3.0,1.0,2022,12,0.286783,0.262643,-0.072022,-0.262643,0.355929,0.180265,-0.212274,-0.180265,0.05997,0.098978,0.11779,0.098978,14083.0,13833.0,0.000000,29,13975.225806,13688.451613,14069.714286,13731.035714,14104.580645,13616.322581,14506.133333,13992.200000
22522763,22.205622,38.561047,MR240,2022-12-30,EL6,κεντρικη ελλαδα,EL64,στερεα ελλαδα,EL645,δωριδος,3.0,3.0,1.0,2022,12,0.286783,0.262643,-0.072022,-0.262643,0.355929,0.180265,-0.212274,-0.180265,0.05997,0.098978,0.11779,0.098978,13802.0,13859.0,0.000000,30,13975.225806,13688.451613,14069.714286,13731.035714,14104.580645,13616.322581,14506.133333,13992.200000
22522764,22.205622,38.561047,MR240,2022-12-31,EL6,κεντρικη ελλαδα,EL64,στερεα ελλαδα,EL645,δωριδος,3.0,3.0,1.0,2022,12,0.286783,0.262643,-0.072022,-0.262643,0.355929,0.180265,-0.212274,-0.180265,0.05997,0.098978,0.11779,0.098978,14103.0,13874.0,0.000000,31,13975.225806,13688.451613,14069.714286,13731.035714,14104.580645,13616.322581,14506.133333,13992.200000

In [7]:
dataset_list = []
groups = data.groupby(['x', 'y', 'year'])

In [14]:
num_of_groups = len(groups)

In [16]:
c = 0

for group, frame in groups:
    print(f"Iteration: {c}/{num_of_groups}", end='\r')
    temp_df = frame.copy()
    temp_df.reset_index(drop=True, inplace=True)
    temp_df['acc_rainfall_1week'] = temp_df['rainfall'].rolling(window=7, min_periods=0).sum()
    temp_df['acc_rainfall_2week'] = temp_df['rainfall'].rolling(window=14, min_periods=0).sum()
    temp_df['acc_rainfall_month'] = temp_df['rainfall'].rolling(window=30, min_periods=0).sum()
    temp_df['acc_rainfall_jan'] = temp_df['dt_placement'].apply(lambda x: temp_df.loc[temp_df['dt_placement'] <= x, 'rainfall'].sum())
    dataset_list.append(temp_df)
    c = c + 1

In [17]:
dataset = pd.concat(dataset_list, ignore_index=True)
dataset.reset_index(drop=True, inplace=True)

In [18]:
dataset

,x,y,cell_code,dt_placement,NUTS1_ID,NUTS1_NAME,NUTS2_ID,NUTS2_NAME,NUTS3_ID,LAU1_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan
0,19.656538,39.718959,HL24,2009-01-01,EL6,κεντρικη ελλαδα,EL62,ιονια νησια,EL622,κερκυρας,4.0,3.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.707780,1,14298.15,13779.6875,14370.0,13839.892857,14353.903226,14010.225806,14543.4,14226.4,6.707780,6.707780,6.707780,6.707780
1,19.656538,39.718959,HL24,2009-01-02,EL6,κεντρικη ελλαδα,EL62,ιονια νησια,EL622,κερκυρας,4.0,3.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.564106,2,14298.15,13779.6875,14370.0,13839.892857,14353.903226,14010.225806,14543.4,14226.4,16.271885,16.271885,16.271885,16.271885
2,19.656538,39.718959,HL24,2009-01-03,EL6,κεντρικη ελλαδα,EL62,ιονια νησια,EL622,κερκυρας,4.0,3.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.859431,3,14298.15,13779.6875,14370.0,13839.892857,14353.903226,14010.225806,14543.4,14226.4,91.131317,91.131317,91.131317,91.131317
3,19.656538,39.718959,HL24,2009-01-04,EL6,κεντρικη ελλαδα,EL62,ιονια νησια,EL622,κερκυρας,4.0,3.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.159674,4,14298.15,13779.6875,14370.0,13839.892857,14353.903226,14010.225806,14543.4,14226.4,105.290990,105.290990,105.290990,105.290990
4,19.656538,39.718959,HL24,2009-01-05,EL6,κεντρικη ελλαδα,EL62,ιονια νησια,EL622,κερκυρας,4.0,3.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,5,14298.15,13779.6875,14370.0,13839.892857,14353.903226,14010.225806,14543.4,14226.4,105.290990,105.290990,105.290990,105.290990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22522760,27.860317,36.529297,VD742,2022-12-27,EL4,"νησια αιγαιου, κρητη",EL42,νοτιο αιγαιο,EL421,συμης,2.0,2.0,1.0,2022,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000
22522761,27.860317,36.529297,VD742,2022-12-28,EL4,"νησια αιγαιου, κρητη",EL42,νοτιο αιγαιο,EL421,συμης,2.0,2.0,1.0,2022,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000
22522762,27.860317,36.529297,VD742,2022-12-29,EL4,"νησια αιγαιου, κρητη",EL42,νοτιο αιγαιο,EL421,συμης,2.0,2.0,1.0,2022,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000
22522763,27.860317,36.529297,VD742,2022-12-30,EL4,"νησια αιγαιου, κρητη",EL42,νοτιο αιγαιο,EL421,συμης,2.0,2.0,1.0,2022,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000
22522764,27.860317,36.529297,VD742,2022-12-31,EL4,"νησια αιγαιου, κρητη",EL42,νοτιο αιγαιο,EL421,συμης,2.0,2.0,1.0,2022,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000

In [19]:
dataset.to_csv('GR_Timeline_2009-2022_filled_mean_rain.csv', encoding='utf-8')