## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../../Modules")

from utils import *

enc = 'utf-8'
dec = 'greek8'
random.seed(0)

In [2]:
NUTS0 = 'GR'
NUTS2 = 'Attica'

In [3]:
nuts2_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Grid_NUTS3.csv', encoding = enc)
nuts2_grid.head()

  NUTS2_ID NUTS2_NAME NUTS3_ID        NUTS3_NAME         x         y
0     EL30     αττικη    EL305  ανατολικη αττικη  24.00727  37.83228
1     EL30     αττικη    EL305  ανατολικη αττικη  23.91651  37.92212
2     EL30     αττικη    EL305  ανατολικη αττικη  23.91651  37.90415
3     EL30     αττικη    EL305  ανατολικη αττικη  23.91651  37.88618
4     EL30     αττικη    EL305  ανατολικη αττικη  23.91651  37.86822

In [4]:
## start and end date is defined from available epidemiological file

In [5]:
start = start_dt = date(2024, 6, 2)
end = end_dt = date(2024, 7, 1)
delta = timedelta(days=1)

In [6]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [7]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2024-06-02 and 2024-07-01
['2024-06-02', '2024-06-03', '2024-06-04', '2024-06-05', '2024-06-06', '2024-06-07', '2024-06-08', '2024-06-09', '2024-06-10', '2024-06-11', '2024-06-12', '2024-06-13', '2024-06-14', '2024-06-15', '2024-06-16', '2024-06-17', '2024-06-18', '2024-06-19', '2024-06-20', '2024-06-21', '2024-06-22', '2024-06-23', '2024-06-24', '2024-06-25', '2024-06-26', '2024-06-27', '2024-06-28', '2024-06-29', '2024-06-30', '2024-07-01']

In [8]:
len(dates)

30

In [9]:
print(f'Total Rows: {len(dates) * len(nuts2_grid)}')

Total Rows: 18720

In [10]:
nuts2_timeline = pd.DataFrame()

In [11]:
data = []
for index, row in nuts2_grid.iterrows():
    for date in dates:
        data.append({'NUTS2_ID': row['NUTS2_ID'], 
                     'NUTS2_NAME': row['NUTS2_NAME'],
                     'NUTS3_ID': row['NUTS3_ID'], 
                     'NUTS3_NAME': row['NUTS3_NAME'], 
                     'x': row['x'], 
                     'y': row['y'], 
                     'dt_placement': date})

nuts2_timeline = pd.DataFrame(data)

In [12]:
nuts2_timeline

,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,x,y,dt_placement
0,EL30,αττικη,EL305,ανατολικη αττικη,24.00727,37.83228,2024-06-02
1,EL30,αττικη,EL305,ανατολικη αττικη,24.00727,37.83228,2024-06-03
2,EL30,αττικη,EL305,ανατολικη αττικη,24.00727,37.83228,2024-06-04
3,EL30,αττικη,EL305,ανατολικη αττικη,24.00727,37.83228,2024-06-05
4,EL30,αττικη,EL305,ανατολικη αττικη,24.00727,37.83228,2024-06-06
...,...,...,...,...,...,...,...
18715,EL30,αττικη,EL307,"πειραιας, νησοι",23.65661,37.95403,2024-06-27
18716,EL30,αττικη,EL307,"πειραιας, νησοι",23.65661,37.95403,2024-06-28
18717,EL30,αττικη,EL307,"πειραιας, νησοι",23.65661,37.95403,2024-06-29
18718,EL30,αττικη,EL307,"πειραιας, νησοι",23.65661,37.95403,2024-06-30
18719,EL30,αττικη,EL307,"πειραιας, νησοι",23.65661,37.95403,2024-07-01

In [13]:
nuts2_timeline['dt_placement'] = pd.to_datetime(nuts2_timeline['dt_placement'])

In [14]:
nuts2_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18720 entries, 0 to 18719
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   NUTS2_ID      18720 non-null  object
 1   NUTS2_NAME    18720 non-null  object
 2   NUTS3_ID      18720 non-null  object
 3   NUTS3_NAME    18720 non-null  object
 4   x             18720 non-null  float64
 5   y             18720 non-null  float64
 6   dt_placement  18720 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(4)
memory usage: 1023.9+ KB

In [15]:
nuts2_timeline.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_NUTS3_2024.csv', index = False)