In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../../Modules")

from utils import *

enc = 'utf-8'
random.seed(0)

In [2]:
GID0 = 'CM'
GID2_NAME = 'Benoue'

In [3]:
gid2_grid = pd.read_csv(f'../../data/{GID2_NAME}/{GID0}_{GID2_NAME}_Grid_GID3.csv', encoding = enc)
gid2_grid.head()

       GID_2 GID2_NAME        GID_3 GID3_NAME         x        y
0  CMR.7.1_1    benoue  CMR.7.1.1_1    bacheo  13.27672  9.65737
1  CMR.7.1_1    benoue  CMR.7.1.1_1    bacheo  13.43610  9.94034
2  CMR.7.1_1    benoue  CMR.7.1.1_1    bacheo  13.43610  9.90890
3  CMR.7.1_1    benoue  CMR.7.1.1_1    bacheo  13.43610  9.87746
4  CMR.7.1_1    benoue  CMR.7.1.1_1    bacheo  13.43610  9.84602

In [4]:
start = start_dt = date(2025, 1, 1)
end = end_dt = date(2025, 1, 31)
delta = timedelta(days=1)

In [5]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [6]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2025-01-01 and 2025-01-31
['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08', '2025-01-09', '2025-01-10', '2025-01-11', '2025-01-12', '2025-01-13', '2025-01-14', '2025-01-15', '2025-01-16', '2025-01-17', '2025-01-18', '2025-01-19', '2025-01-20', '2025-01-21', '2025-01-22', '2025-01-23', '2025-01-24', '2025-01-25', '2025-01-26', '2025-01-27', '2025-01-28', '2025-01-29', '2025-01-30', '2025-01-31']

In [7]:
len(dates)

31

In [9]:
print(f'Total Rows: {len(dates) * len(gid2_grid)}')

Total Rows: 25575

In [10]:
gid2_timeline = pd.DataFrame()

In [11]:
data = []
for index, row in gid2_grid.iterrows():
    for date in dates:
        data.append({'GID_2': row['GID_2'], 
                     'GID2_NAME': row['GID2_NAME'],
                     'GID_3': row['GID_3'], 
                     'GID3_NAME': row['GID3_NAME'], 
                     'x': row['x'], 
                     'y': row['y'], 
                     'dt_placement': date})

gid2_timeline = pd.DataFrame(data)

In [12]:
gid2_timeline

,GID_2,GID2_NAME,GID_3,GID3_NAME,x,y,dt_placement
0,CMR.7.1_1,benoue,CMR.7.1.1_1,bacheo,13.27672,9.65737,2025-01-01
1,CMR.7.1_1,benoue,CMR.7.1.1_1,bacheo,13.27672,9.65737,2025-01-02
2,CMR.7.1_1,benoue,CMR.7.1.1_1,bacheo,13.27672,9.65737,2025-01-03
3,CMR.7.1_1,benoue,CMR.7.1.1_1,bacheo,13.27672,9.65737,2025-01-04
4,CMR.7.1_1,benoue,CMR.7.1.1_1,bacheo,13.27672,9.65737,2025-01-05
...,...,...,...,...,...,...,...
25570,CMR.7.1_1,benoue,CMR.7.1.12_1,touroua,12.92331,9.36878,2025-01-27
25571,CMR.7.1_1,benoue,CMR.7.1.12_1,touroua,12.92331,9.36878,2025-01-28
25572,CMR.7.1_1,benoue,CMR.7.1.12_1,touroua,12.92331,9.36878,2025-01-29
25573,CMR.7.1_1,benoue,CMR.7.1.12_1,touroua,12.92331,9.36878,2025-01-30
25574,CMR.7.1_1,benoue,CMR.7.1.12_1,touroua,12.92331,9.36878,2025-01-31

In [13]:
gid2_timeline['dt_placement'] = pd.to_datetime(gid2_timeline['dt_placement'])

In [15]:
gid2_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25575 entries, 0 to 25574
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   GID_2         25575 non-null  object
 1   GID2_NAME     25575 non-null  object
 2   GID_3         25575 non-null  object
 3   GID3_NAME     25575 non-null  object
 4   x             25575 non-null  float64
 5   y             25575 non-null  float64
 6   dt_placement  25575 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(4)
memory usage: 1.4+ MB

In [16]:
gid2_timeline.to_csv(f'../../data/{GID2_NAME}/{GID0}_{GID2_NAME}_Timeline_GID3_test.csv', index = False)