## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../../Modules")

from utils import *

enc = 'utf-8'
dec = 'greek8'
random.seed(0)

In [2]:
NUTS0 = 'GR'
NUTS2 = 'Thessaly'

In [3]:
nuts2_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Grid_NUTS3.csv', encoding = enc)
nuts2_grid.head()

  NUTS2_ID NUTS2_NAME NUTS3_ID         NUTS3_NAME         x         y
0     EL61   θεσσαλια    EL611  καρδιτσα, τρικαλα  21.19021  39.65516
1     EL61   θεσσαλια    EL611  καρδιτσα, τρικαλα  21.88403  39.36769
2     EL61   θεσσαλια    EL611  καρδιτσα, τρικαλα  21.88403  39.33176
3     EL61   θεσσαλια    EL611  καρδιτσα, τρικαλα  21.88403  39.29583
4     EL61   θεσσαλια    EL611  καρδιτσα, τρικαλα  21.88403  39.25989

In [4]:
## start and end date is defined from available epidemiological file

In [5]:
start = start_dt = date(2024, 7, 2)
end = end_dt = date(2024, 8, 1)
delta = timedelta(days=1)

In [6]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [7]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2024-07-02 and 2024-08-01
['2024-07-02', '2024-07-03', '2024-07-04', '2024-07-05', '2024-07-06', '2024-07-07', '2024-07-08', '2024-07-09', '2024-07-10', '2024-07-11', '2024-07-12', '2024-07-13', '2024-07-14', '2024-07-15', '2024-07-16', '2024-07-17', '2024-07-18', '2024-07-19', '2024-07-20', '2024-07-21', '2024-07-22', '2024-07-23', '2024-07-24', '2024-07-25', '2024-07-26', '2024-07-27', '2024-07-28', '2024-07-29', '2024-07-30', '2024-07-31', '2024-08-01']

In [8]:
len(dates)

31

In [9]:
print(f'Total Rows: {len(dates) * len(nuts2_grid)}')

Total Rows: 21514

In [10]:
nuts2_timeline = pd.DataFrame()

In [11]:
data = []
for index, row in nuts2_grid.iterrows():
    for date in dates:
        data.append({'NUTS2_ID': row['NUTS2_ID'], 
                     'NUTS2_NAME': row['NUTS2_NAME'],
                     'NUTS3_ID': row['NUTS3_ID'], 
                     'NUTS3_NAME': row['NUTS3_NAME'], 
                     'x': row['x'], 
                     'y': row['y'], 
                     'dt_placement': date})

nuts2_timeline = pd.DataFrame(data)

In [12]:
nuts2_timeline

,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,x,y,dt_placement
0,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-07-02
1,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-07-03
2,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-07-04
3,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-07-05
4,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-07-06
...,...,...,...,...,...,...,...
21509,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2024-07-28
21510,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2024-07-29
21511,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2024-07-30
21512,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2024-07-31
21513,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2024-08-01

In [13]:
nuts2_timeline['dt_placement'] = pd.to_datetime(nuts2_timeline['dt_placement'])

In [14]:
nuts2_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21514 entries, 0 to 21513
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   NUTS2_ID      21514 non-null  object
 1   NUTS2_NAME    21514 non-null  object
 2   NUTS3_ID      21514 non-null  object
 3   NUTS3_NAME    21514 non-null  object
 4   x             21514 non-null  float64
 5   y             21514 non-null  float64
 6   dt_placement  21514 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(4)
memory usage: 1.1+ MB

In [15]:
nuts2_timeline.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_NUTS3_2024.csv', index = False)