In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../utils")

from plots import *
from string_handling import *

enc = 'utf-8' 

random.seed(0)
np.random.seed(0)

pd.set_option('display.max_columns', None)

In [2]:
cm_extnord_grid = pd.read_csv('../data/CM_ExtNord_Grid.csv', encoding=enc)
cm_extnord_grid.head()

          x         y          GID0          GID1    GID2      GID3
0  13.43483  10.10446  extreme nord  mayo-tsanaga  bourha  maboudji
1  13.45125  10.14959  extreme nord  mayo-tsanaga  bourha  boukoula
2  13.45125  10.16755  extreme nord  mayo-tsanaga  bourha  boukoula
3  13.46950  10.13162  extreme nord  mayo-tsanaga  bourha  boukoula
4  13.46950  10.14959  extreme nord  mayo-tsanaga  bourha  boukoula

In [3]:
start = start_dt = date(2014, 1, 1)
end = end_dt = date(2024, 12, 31)
delta = timedelta(days=1)

In [4]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [5]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2014-01-01 and 2024-12-31

In [6]:
len(dates)

4018

In [7]:
print(f'Total Rows: {len(dates) * len(cm_extnord_grid)}')

Total Rows: 8321278

In [8]:
cm_timeline = pd.DataFrame()

In [9]:
data = []
for index, row in cm_extnord_grid.iterrows():
    for date in dates:
        data.append({'x': row['x'], 
                     'y': row['y'],
                     'GID0': row['GID0'], 
                     'GID1': row['GID1'],
                     'GID2': row['GID2'], 
                     'GID3': row['GID3'],  
                     'dt_placement': date})

In [10]:
cm_timeline = pd.DataFrame(data)

In [11]:
cm_timeline

,x,y,GID0,GID1,GID2,GID3,dt_placement
0,13.43483,10.10446,extreme nord,mayo-tsanaga,bourha,maboudji,2014-01-01
1,13.43483,10.10446,extreme nord,mayo-tsanaga,bourha,maboudji,2014-01-02
2,13.43483,10.10446,extreme nord,mayo-tsanaga,bourha,maboudji,2014-01-03
3,13.43483,10.10446,extreme nord,mayo-tsanaga,bourha,maboudji,2014-01-04
4,13.43483,10.10446,extreme nord,mayo-tsanaga,bourha,maboudji,2014-01-05
...,...,...,...,...,...,...,...
8321273,15.57371,10.02477,extreme nord,mayo-danay,guere,nouldaina,2024-12-27
8321274,15.57371,10.02477,extreme nord,mayo-danay,guere,nouldaina,2024-12-28
8321275,15.57371,10.02477,extreme nord,mayo-danay,guere,nouldaina,2024-12-29
8321276,15.57371,10.02477,extreme nord,mayo-danay,guere,nouldaina,2024-12-30
8321277,15.57371,10.02477,extreme nord,mayo-danay,guere,nouldaina,2024-12-31

In [12]:
cm_timeline['dt_placement'] = pd.to_datetime(cm_timeline['dt_placement'])
cm_timeline['year'] = cm_timeline['dt_placement'].apply(lambda x: x.year)

In [13]:
cm_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8321278 entries, 0 to 8321277
Data columns (total 8 columns):
 #   Column        Dtype
---  ------        -----
 0   x             float64
 1   y             float64
 2   GID0          object
 3   GID1          object
 4   GID2          object
 5   GID3          object
 6   dt_placement  datetime64[ns]
 7   year          int64
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 507.9+ MB

In [14]:
years = cm_timeline.year.unique().tolist()

In [15]:
for item in years:
    cm_towrite = cm_timeline[cm_timeline.year == item].drop(columns = ['year'])
    print(f'Year: {item}, Timeline Shape: {cm_towrite.shape}')
    cm_towrite.to_csv(f'../data/CM_ExtNord_Timeline_{item}.csv', index = False)

Year: 2014, Timeline Shape: (755915, 7)
Year: 2015, Timeline Shape: (755915, 7)
Year: 2016, Timeline Shape: (757986, 7)
Year: 2017, Timeline Shape: (755915, 7)
Year: 2018, Timeline Shape: (755915, 7)
Year: 2019, Timeline Shape: (755915, 7)
Year: 2020, Timeline Shape: (757986, 7)
Year: 2021, Timeline Shape: (755915, 7)
Year: 2022, Timeline Shape: (755915, 7)
Year: 2023, Timeline Shape: (755915, 7)
Year: 2024, Timeline Shape: (757986, 7)