In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../utils")

from plots import *
from string_handling import *

enc = 'utf-8' 

random.seed(0)
np.random.seed(0)

pd.set_option('display.max_columns', None)

In [2]:
cm_extnord_grid = pd.read_csv('../../data/ExtNord/CM_ExtNord_Grid.csv', encoding=enc)
cm_extnord_grid.head()

          x         y          GID0          GID1    GID2      GID3
0  13.43483  10.10446  extreme nord  mayo-tsanaga  bourha  maboudji
1  13.45125  10.14959  extreme nord  mayo-tsanaga  bourha  boukoula
2  13.45125  10.16755  extreme nord  mayo-tsanaga  bourha  boukoula
3  13.46950  10.13162  extreme nord  mayo-tsanaga  bourha  boukoula
4  13.46950  10.14959  extreme nord  mayo-tsanaga  bourha  boukoula

In [ ]:
start = start_dt = date(2013, 1, 1)
end = end_dt = date(2024, 12, 31)
delta = timedelta(days=1)

In [4]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [5]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2013-01-01 and 2013-12-31
['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08', '2013-01-09', '2013-01-10', '2013-01-11', '2013-01-12', '2013-01-13', '2013-01-14', '2013-01-15', '2013-01-16', '2013-01-17', '2013-01-18', '2013-01-19', '2013-01-20', '2013-01-21', '2013-01-22', '2013-01-23', '2013-01-24', '2013-01-25', '2013-01-26', '2013-01-27', '2013-01-28', '2013-01-29', '2013-01-30', '2013-01-31', '2013-02-01', '2013-02-02', '2013-02-03', '2013-02-04', '2013-02-05', '2013-02-06', '2013-02-07', '2013-02-08', '2013-02-09', '2013-02-10', '2013-02-11', '2013-02-12', '2013-02-13', '2013-02-14', '2013-02-15', '2013-02-16', '2013-02-17', '2013-02-18', '2013-02-19', '2013-02-20', '2013-02-21', '2013-02-22', '2013-02-23', '2013-02-24', '2013-02-25', '2013-02-26', '2013-02-27', '2013-02-28', '2013-03-01', '2013-03-02', '2013-03-03', '2013-03-04', '2013-03-05', '2013-03-06', '2013-03-07', '2013-03-08', '2013-03-09', '2013-03-10', '2013-03-11', '2013-03-12', '2013-03-13', '2013-03-14', '2013-03-15', '2013-03-16', '2013-03-17', '2013-03-18', '2013-03-19', '2013-03-20', '2013-03-21', '2013-03-22', '2013-03-23', '2013-03-24', '2013-03-25', '2013-03-26', '2013-03-27', '2013-03-28', '2013-03-29', '2013-03-30', '2013-03-31', '2013-04-01', '2013-04-02', '2013-04-03', '2013-04-04', '2013-04-05', '2013-04-06', '2013-04-07', '2013-04-08', '2013-04-09', '2013-04-10', '2013-04-11', '2013-04-12', '2013-04-13', '2013-04-14', '2013-04-15', '2013-04-16', '2013-04-17', '2013-04-18', '2013-04-19', '2013-04-20', '2013-04-21', '2013-04-22', '2013-04-23', '2013-04-24', '2013-04-25', '2013-04-26', '2013-04-27', '2013-04-28', '2013-04-29', '2013-04-30', '2013-05-01', '2013-05-02', '2013-05-03', '2013-05-04', '2013-05-05', '2013-05-06', '2013-05-07', '2013-05-08', '2013-05-09', '2013-05-10', '2013-05-11', '2013-05-12', '2013-05-13', '2013-05-14', '2013-05-15', '2013-05-16', '2013-05-17', '2013-05-18', '2013-05-19', '2013-05-20', '2013-05-21', '2013-05-22', '2013-05-23', '2013-05-24', '2013-05-25', '2013-05-26', '2013-05-27', '2013-05-28', '2013-05-29', '2013-05-30', '2013-05-31', '2013-06-01', '2013-06-02', '2013-06-03', '2013-06-04', '2013-06-05', '2013-06-06', '2013-06-07', '2013-06-08', '2013-06-09', '2013-06-10', '2013-06-11', '2013-06-12', '2013-06-13', '2013-06-14', '2013-06-15', '2013-06-16', '2013-06-17', '2013-06-18', '2013-06-19', '2013-06-20', '2013-06-21', '2013-06-22', '2013-06-23', '2013-06-24', '2013-06-25', '2013-06-26', '2013-06-27', '2013-06-28', '2013-06-29', '2013-06-30', '2013-07-01', '2013-07-02', '2013-07-03', '2013-07-04', '2013-07-05', '2013-07-06', '2013-07-07', '2013-07-08', '2013-07-09', '2013-07-10', '2013-07-11', '2013-07-12', '2013-07-13', '2013-07-14', '2013-07-15', '2013-07-16', '2013-07-17', '2013-07-18', '2013-07-19', '2013-07-20', '2013-07-21', '2013-07-22', '2013-07-23', '2013-07-24', '2013-07-25', '2013-07-26', '2013-07-27', '2013-07-28', '2013-07-29', '2013-07-30', '2013-07-31', '2013-08-01', '2013-08-02', '2013-08-03', '2013-08-04', '2013-08-05', '2013-08-06', '2013-08-07', '2013-08-08', '2013-08-09', '2013-08-10', '2013-08-11', '2013-08-12', '2013-08-13', '2013-08-14', '2013-08-15', '2013-08-16', '2013-08-17', '2013-08-18', '2013-08-19', '2013-08-20', '2013-08-21', '2013-08-22', '2013-08-23', '2013-08-24', '2013-08-25', '2013-08-26', '2013-08-27', '2013-08-28', '2013-08-29', '2013-08-30', '2013-08-31', '2013-09-01', '2013-09-02', '2013-09-03', '2013-09-04', '2013-09-05', '2013-09-06', '2013-09-07', '2013-09-08', '2013-09-09', '2013-09-10', '2013-09-11', '2013-09-12', '2013-09-13', '2013-09-14', '2013-09-15', '2013-09-16', '2013-09-17', '2013-09-18', '2013-09-19', '2013-09-20', '2013-09-21', '2013-09-22', '2013-09-23', '2013-09-24', '2013-09-25', '2013-09-26', '2013-09-27', '2013-09-28', '2013-09-29', '2013-09-30', '2013-10-01', '2013-10-02', '2013-10-03', '2013-10-04', '2013-10-05', '2013-10-06', '2013-10-07', '2013-10-08', '2013-10-09', '2013-10-10', '2013-10-11', '2013-10-12', '2013-10-13', '2013-10-14', '2013-10-15', '2013-10-16', '2013-10-17', '2013-10-18', '2013-10-19', '2013-10-20', '2013-10-21', '2013-10-22', '2013-10-23', '2013-10-24', '2013-10-25', '2013-10-26', '2013-10-27', '2013-10-28', '2013-10-29', '2013-10-30', '2013-10-31', '2013-11-01', '2013-11-02', '2013-11-03', '2013-11-04', '2013-11-05', '2013-11-06', '2013-11-07', '2013-11-08', '2013-11-09', '2013-11-10', '2013-11-11', '2013-11-12', '2013-11-13', '2013-11-14', '2013-11-15', '2013-11-16', '2013-11-17', '2013-11-18', '2013-11-19', '2013-11-20', '2013-11-21', '2013-11-22', '2013-11-23', '2013-11-24', '2013-11-25', '2013-11-26', '2013-11-27', '2013-11-28', '2013-11-29', '2013-11-30', '2013-12-01', '2013-12-02', '2013-12-03', '2013-12-04', '2013-12-05', '2013-12-06', '2013-12-07', '2013-12-08', '2013-12-09', '2013-12-10', '2013-12-11', '2013-12-12', '2013-12-13', '2013-12-14', '2013-12-15', '2013-12-16', '2013-12-17', '2013-12-18', '2013-12-19', '2013-12-20', '2013-12-21', '2013-12-22', '2013-12-23', '2013-12-24', '2013-12-25', '2013-12-26', '2013-12-27', '2013-12-28', '2013-12-29', '2013-12-30', '2013-12-31']

In [6]:
len(dates)

365

In [7]:
print(f'Total Rows: {len(dates) * len(cm_extnord_grid)}')

Total Rows: 755915

In [8]:
cm_timeline = pd.DataFrame()

In [9]:
data = []
for index, row in cm_extnord_grid.iterrows():
    for date in dates:
        data.append({'x': row['x'], 
                     'y': row['y'],
                     'GID0': row['GID0'], 
                     'GID1': row['GID1'],
                     'GID2': row['GID2'], 
                     'GID3': row['GID3'],  
                     'dt_placement': date})

In [10]:
cm_timeline = pd.DataFrame(data)

In [11]:
cm_timeline

,x,y,GID0,GID1,GID2,GID3,dt_placement
0,13.43483,10.10446,extreme nord,mayo-tsanaga,bourha,maboudji,2013-01-01
1,13.43483,10.10446,extreme nord,mayo-tsanaga,bourha,maboudji,2013-01-02
2,13.43483,10.10446,extreme nord,mayo-tsanaga,bourha,maboudji,2013-01-03
3,13.43483,10.10446,extreme nord,mayo-tsanaga,bourha,maboudji,2013-01-04
4,13.43483,10.10446,extreme nord,mayo-tsanaga,bourha,maboudji,2013-01-05
...,...,...,...,...,...,...,...
755910,15.57371,10.02477,extreme nord,mayo-danay,guere,nouldaina,2013-12-27
755911,15.57371,10.02477,extreme nord,mayo-danay,guere,nouldaina,2013-12-28
755912,15.57371,10.02477,extreme nord,mayo-danay,guere,nouldaina,2013-12-29
755913,15.57371,10.02477,extreme nord,mayo-danay,guere,nouldaina,2013-12-30
755914,15.57371,10.02477,extreme nord,mayo-danay,guere,nouldaina,2013-12-31

In [12]:
cm_timeline['dt_placement'] = pd.to_datetime(cm_timeline['dt_placement'])
cm_timeline['year'] = cm_timeline['dt_placement'].apply(lambda x: x.year)

In [13]:
cm_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 755915 entries, 0 to 755914
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   x             755915 non-null  float64
 1   y             755915 non-null  float64
 2   GID0          755915 non-null  object
 3   GID1          755915 non-null  object
 4   GID2          755915 non-null  object
 5   GID3          755915 non-null  object
 6   dt_placement  755915 non-null  datetime64[ns]
 7   year          755915 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 46.1+ MB

In [14]:
years = cm_timeline.year.unique().tolist()

In [15]:
for item in years:
    cm_towrite = cm_timeline[cm_timeline.year == item].drop(columns = ['year'])
    print(f'Year: {item}, Timeline Shape: {cm_towrite.shape}')
    cm_towrite.to_csv(f'../../data/ExtNord/CM_ExtNord_Timeline_{item}.csv', index = False)

Year: 2013, Timeline Shape: (755915, 7)