In [ ]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../utils")

from plots import *
from string_handling import *

enc = 'utf-8' 

random.seed(0)
np.random.seed(0)

pd.set_option('display.max_columns', None)

REGION = 'ExtNord'

In [ ]:
cm_extnord_grid = pd.read_csv('../../data/{REGION}/CM_{REGION}_Grid.csv', encoding=enc)
cm_extnord_grid.head()

          x         y          GID0          GID1    GID2      GID3
0  13.43483  10.10446  extreme nord  mayo-tsanaga  bourha  maboudji
1  13.45125  10.14959  extreme nord  mayo-tsanaga  bourha  boukoula
2  13.45125  10.16755  extreme nord  mayo-tsanaga  bourha  boukoula
3  13.46950  10.13162  extreme nord  mayo-tsanaga  bourha  boukoula
4  13.46950  10.14959  extreme nord  mayo-tsanaga  bourha  boukoula

In [3]:
start = start_dt = date(2025, 1, 1)
end = end_dt = date(2025, 8, 31)
delta = timedelta(days=1)

In [4]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [5]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2025-01-01 and 2025-08-31
['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08', '2025-01-09', '2025-01-10', '2025-01-11', '2025-01-12', '2025-01-13', '2025-01-14', '2025-01-15', '2025-01-16', '2025-01-17', '2025-01-18', '2025-01-19', '2025-01-20', '2025-01-21', '2025-01-22', '2025-01-23', '2025-01-24', '2025-01-25', '2025-01-26', '2025-01-27', '2025-01-28', '2025-01-29', '2025-01-30', '2025-01-31', '2025-02-01', '2025-02-02', '2025-02-03', '2025-02-04', '2025-02-05', '2025-02-06', '2025-02-07', '2025-02-08', '2025-02-09', '2025-02-10', '2025-02-11', '2025-02-12', '2025-02-13', '2025-02-14', '2025-02-15', '2025-02-16', '2025-02-17', '2025-02-18', '2025-02-19', '2025-02-20', '2025-02-21', '2025-02-22', '2025-02-23', '2025-02-24', '2025-02-25', '2025-02-26', '2025-02-27', '2025-02-28', '2025-03-01', '2025-03-02', '2025-03-03', '2025-03-04', '2025-03-05', '2025-03-06', '2025-03-07', '2025-03-08', '2025-03-09', '2025-03-10', '2025-03-11', '2025-03-12', '2025-03-13', '2025-03-14', '2025-03-15', '2025-03-16', '2025-03-17', '2025-03-18', '2025-03-19', '2025-03-20', '2025-03-21', '2025-03-22', '2025-03-23', '2025-03-24', '2025-03-25', '2025-03-26', '2025-03-27', '2025-03-28', '2025-03-29', '2025-03-30', '2025-03-31', '2025-04-01', '2025-04-02', '2025-04-03', '2025-04-04', '2025-04-05', '2025-04-06', '2025-04-07', '2025-04-08', '2025-04-09', '2025-04-10', '2025-04-11', '2025-04-12', '2025-04-13', '2025-04-14', '2025-04-15', '2025-04-16', '2025-04-17', '2025-04-18', '2025-04-19', '2025-04-20', '2025-04-21', '2025-04-22', '2025-04-23', '2025-04-24', '2025-04-25', '2025-04-26', '2025-04-27', '2025-04-28', '2025-04-29', '2025-04-30', '2025-05-01', '2025-05-02', '2025-05-03', '2025-05-04', '2025-05-05', '2025-05-06', '2025-05-07', '2025-05-08', '2025-05-09', '2025-05-10', '2025-05-11', '2025-05-12', '2025-05-13', '2025-05-14', '2025-05-15', '2025-05-16', '2025-05-17', '2025-05-18', '2025-05-19', '2025-05-20', '2025-05-21', '2025-05-22', '2025-05-23', '2025-05-24', '2025-05-25', '2025-05-26', '2025-05-27', '2025-05-28', '2025-05-29', '2025-05-30', '2025-05-31', '2025-06-01', '2025-06-02', '2025-06-03', '2025-06-04', '2025-06-05', '2025-06-06', '2025-06-07', '2025-06-08', '2025-06-09', '2025-06-10', '2025-06-11', '2025-06-12', '2025-06-13', '2025-06-14', '2025-06-15', '2025-06-16', '2025-06-17', '2025-06-18', '2025-06-19', '2025-06-20', '2025-06-21', '2025-06-22', '2025-06-23', '2025-06-24', '2025-06-25', '2025-06-26', '2025-06-27', '2025-06-28', '2025-06-29', '2025-06-30', '2025-07-01', '2025-07-02', '2025-07-03', '2025-07-04', '2025-07-05', '2025-07-06', '2025-07-07', '2025-07-08', '2025-07-09', '2025-07-10', '2025-07-11', '2025-07-12', '2025-07-13', '2025-07-14', '2025-07-15', '2025-07-16', '2025-07-17', '2025-07-18', '2025-07-19', '2025-07-20', '2025-07-21', '2025-07-22', '2025-07-23', '2025-07-24', '2025-07-25', '2025-07-26', '2025-07-27', '2025-07-28', '2025-07-29', '2025-07-30', '2025-07-31', '2025-08-01', '2025-08-02', '2025-08-03', '2025-08-04', '2025-08-05', '2025-08-06', '2025-08-07', '2025-08-08', '2025-08-09', '2025-08-10', '2025-08-11', '2025-08-12', '2025-08-13', '2025-08-14', '2025-08-15', '2025-08-16', '2025-08-17', '2025-08-18', '2025-08-19', '2025-08-20', '2025-08-21', '2025-08-22', '2025-08-23', '2025-08-24', '2025-08-25', '2025-08-26', '2025-08-27', '2025-08-28', '2025-08-29', '2025-08-30', '2025-08-31']

In [6]:
len(dates)

243

In [7]:
print(f'Total Rows: {len(dates) * len(cm_extnord_grid)}')

Total Rows: 503253

In [8]:
cm_timeline = pd.DataFrame()

In [9]:
data = []
for index, row in cm_extnord_grid.iterrows():
    for date in dates:
        data.append({'x': row['x'], 
                     'y': row['y'],
                     'GID0': row['GID0'], 
                     'GID1': row['GID1'],
                     'GID2': row['GID2'], 
                     'GID3': row['GID3'],  
                     'dt_placement': date})

In [10]:
cm_timeline = pd.DataFrame(data)

In [11]:
cm_timeline

,x,y,GID0,GID1,GID2,GID3,dt_placement
0,13.43483,10.10446,extreme nord,mayo-tsanaga,bourha,maboudji,2025-01-01
1,13.43483,10.10446,extreme nord,mayo-tsanaga,bourha,maboudji,2025-01-02
2,13.43483,10.10446,extreme nord,mayo-tsanaga,bourha,maboudji,2025-01-03
3,13.43483,10.10446,extreme nord,mayo-tsanaga,bourha,maboudji,2025-01-04
4,13.43483,10.10446,extreme nord,mayo-tsanaga,bourha,maboudji,2025-01-05
...,...,...,...,...,...,...,...
503248,15.57371,10.02477,extreme nord,mayo-danay,guere,nouldaina,2025-08-27
503249,15.57371,10.02477,extreme nord,mayo-danay,guere,nouldaina,2025-08-28
503250,15.57371,10.02477,extreme nord,mayo-danay,guere,nouldaina,2025-08-29
503251,15.57371,10.02477,extreme nord,mayo-danay,guere,nouldaina,2025-08-30
503252,15.57371,10.02477,extreme nord,mayo-danay,guere,nouldaina,2025-08-31

In [12]:
cm_timeline['dt_placement'] = pd.to_datetime(cm_timeline['dt_placement'])
cm_timeline['year'] = cm_timeline['dt_placement'].apply(lambda x: x.year)

In [13]:
cm_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503253 entries, 0 to 503252
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   x             503253 non-null  float64
 1   y             503253 non-null  float64
 2   GID0          503253 non-null  object
 3   GID1          503253 non-null  object
 4   GID2          503253 non-null  object
 5   GID3          503253 non-null  object
 6   dt_placement  503253 non-null  datetime64[ns]
 7   year          503253 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 30.7+ MB

In [14]:
years = cm_timeline.year.unique().tolist()

In [15]:
years

[2025]

In [ ]:
## change the month here

for item in years:
    cm_towrite = cm_timeline[cm_timeline.year == item].drop(columns = ['year'])
    print(f'Year: {item}, Timeline Shape: {cm_towrite.shape}')
    cm_towrite.to_csv(f'../../data/{REGION}/CM_{REGION}_Timeline_{item}_08.csv', index = False)

Year: 2025, Timeline Shape: (503253, 7)