## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../../Modules")

from utils import *

enc = 'utf-8'
dec = 'greek8'
random.seed(0)

In [2]:
NUTS0 = 'GR'
NUTS2 = 'Thessaly'

In [3]:
nuts2_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Grid_NUTS3.csv', encoding = enc)
nuts2_grid.head()

  NUTS2_ID NUTS2_NAME NUTS3_ID         NUTS3_NAME         x         y
0     EL61   θεσσαλια    EL611  καρδιτσα, τρικαλα  21.19021  39.65516
1     EL61   θεσσαλια    EL611  καρδιτσα, τρικαλα  21.88403  39.36769
2     EL61   θεσσαλια    EL611  καρδιτσα, τρικαλα  21.88403  39.33176
3     EL61   θεσσαλια    EL611  καρδιτσα, τρικαλα  21.88403  39.29583
4     EL61   θεσσαλια    EL611  καρδιτσα, τρικαλα  21.88403  39.25989

In [4]:
## start and end date is defined from available epidemiological file

In [5]:
start = start_dt = date(2024, 1, 1)
end = end_dt = date(2024, 5, 1)
delta = timedelta(days=1)

In [6]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [7]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2024-01-01 and 2024-05-01
['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08', '2024-01-09', '2024-01-10', '2024-01-11', '2024-01-12', '2024-01-13', '2024-01-14', '2024-01-15', '2024-01-16', '2024-01-17', '2024-01-18', '2024-01-19', '2024-01-20', '2024-01-21', '2024-01-22', '2024-01-23', '2024-01-24', '2024-01-25', '2024-01-26', '2024-01-27', '2024-01-28', '2024-01-29', '2024-01-30', '2024-01-31', '2024-02-01', '2024-02-02', '2024-02-03', '2024-02-04', '2024-02-05', '2024-02-06', '2024-02-07', '2024-02-08', '2024-02-09', '2024-02-10', '2024-02-11', '2024-02-12', '2024-02-13', '2024-02-14', '2024-02-15', '2024-02-16', '2024-02-17', '2024-02-18', '2024-02-19', '2024-02-20', '2024-02-21', '2024-02-22', '2024-02-23', '2024-02-24', '2024-02-25', '2024-02-26', '2024-02-27', '2024-02-28', '2024-02-29', '2024-03-01', '2024-03-02', '2024-03-03', '2024-03-04', '2024-03-05', '2024-03-06', '2024-03-07', '2024-03-08', '2024-03-09', '2024-03-10', '2024-03-11', '2024-03-12', '2024-03-13', '2024-03-14', '2024-03-15', '2024-03-16', '2024-03-17', '2024-03-18', '2024-03-19', '2024-03-20', '2024-03-21', '2024-03-22', '2024-03-23', '2024-03-24', '2024-03-25', '2024-03-26', '2024-03-27', '2024-03-28', '2024-03-29', '2024-03-30', '2024-03-31', '2024-04-01', '2024-04-02', '2024-04-03', '2024-04-04', '2024-04-05', '2024-04-06', '2024-04-07', '2024-04-08', '2024-04-09', '2024-04-10', '2024-04-11', '2024-04-12', '2024-04-13', '2024-04-14', '2024-04-15', '2024-04-16', '2024-04-17', '2024-04-18', '2024-04-19', '2024-04-20', '2024-04-21', '2024-04-22', '2024-04-23', '2024-04-24', '2024-04-25', '2024-04-26', '2024-04-27', '2024-04-28', '2024-04-29', '2024-04-30', '2024-05-01']

In [8]:
len(dates)

122

In [9]:
print(f'Total Rows: {len(dates) * len(nuts2_grid)}')

Total Rows: 84668

In [10]:
nuts2_timeline = pd.DataFrame()

In [11]:
data = []
for index, row in nuts2_grid.iterrows():
    for date in dates:
        data.append({'NUTS2_ID': row['NUTS2_ID'], 
                     'NUTS2_NAME': row['NUTS2_NAME'],
                     'NUTS3_ID': row['NUTS3_ID'], 
                     'NUTS3_NAME': row['NUTS3_NAME'], 
                     'x': row['x'], 
                     'y': row['y'], 
                     'dt_placement': date})

nuts2_timeline = pd.DataFrame(data)

In [12]:
nuts2_timeline

,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,x,y,dt_placement
0,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-01-01
1,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-01-02
2,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-01-03
3,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-01-04
4,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2024-01-05
...,...,...,...,...,...,...,...
84663,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2024-04-27
84664,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2024-04-28
84665,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2024-04-29
84666,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2024-04-30
84667,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2024-05-01

In [13]:
nuts2_timeline['dt_placement'] = pd.to_datetime(nuts2_timeline['dt_placement'])

In [14]:
nuts2_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84668 entries, 0 to 84667
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   NUTS2_ID      84668 non-null  object
 1   NUTS2_NAME    84668 non-null  object
 2   NUTS3_ID      84668 non-null  object
 3   NUTS3_NAME    84668 non-null  object
 4   x             84668 non-null  float64
 5   y             84668 non-null  float64
 6   dt_placement  84668 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(4)
memory usage: 4.5+ MB

In [15]:
nuts2_timeline.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_NUTS3_2024.csv', index = False)