In [1]:
import pandas as pd

enc = 'utf-8'
dec = 'greek8'

pd.options.display.max_columns = None
pd.options.display.max_rows = 10

In [4]:
COUNTRY_CODE = 'GR'
REGION = 'Attica'
REGION_WNV = 'αττικης'

In [3]:
data = pd.read_csv(f'data/{COUNTRY_CODE}_WNV_cases_2010-2021_processed.csv', encoding = enc)
data.head(5)

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,lau2,age,sex
0,2010-07-28,2010,7,28,κεντρικης μακεδονιας,θεσσαλονικης,θεσσαλονικης,"παπαφη, θεσσαλονικη",75,f
1,2010-07-22,2010,7,22,κεντρικης μακεδονιας,ημαθιας,βεροιας,βεροια,78,m
2,2010-07-24,2010,7,24,κεντρικης μακεδονιας,κιλκις,κιλκις,λεβεντοχωρι,70,f
3,2010-07-30,2010,7,30,κεντρικης μακεδονιας,κιλκις,κιλκις,καμπανη,74,m
4,2010-07-06,2010,7,6,κεντρικης μακεδονιας,σερρων,ηρακλειας,ποντισμενο,19,f

In [5]:
df = data[data['nuts2'].isin([REGION_WNV])].copy()

In [6]:
df.reset_index(drop = True, inplace = True)

In [7]:
df

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,lau2,age,sex
0,2011-07-28,2011,7,28,αττικης,ανατολικης αττικης,μαραθωνος,μαραθωνας,25,m
1,2011-07-31,2011,7,31,αττικης,ανατολικης αττικης,μαραθωνος,μαραθωνας,70,f
2,2011-07-27,2011,7,27,αττικης,ανατολικης αττικης,μαραθωνος,μαραθωνας,74,m
3,2011-07-27,2011,7,27,αττικης,ανατολικης αττικης,μαραθωνος,μαραθωνας,66,m
4,2011-07-25,2011,7,25,αττικης,ανατολικης αττικης,σπατων-αρτεμιδος,"""αγια κυριακη σπατων"", αρτεμιδα",70,m
...,...,...,...,...,...,...,...,...,...,...
291,2020-07-20,2020,7,20,αττικης,ανατολικης αττικης,μαραθωνος,σχοινιας,76,m
292,2020-08-03,2020,8,3,αττικης,ανατολικης αττικης,μαραθωνος,μαραθωνας,58,m
293,2021-07-23,2021,7,23,αττικης,ανατολικης αττικης,παλληνης,παλληνη,60,m
294,2021-08-09,2021,8,9,αττικης,ανατολικης αττικης,σπατων-αρτεμιδος,σπατα,70,m
295,2021-09-15,2021,9,15,αττικης,ανατολικης αττικης,σπατων-αρτεμιδος,αρτεμιδα,55,m

In [8]:
attica_lau1 = df['lau1'].drop_duplicates().sort_values().tolist()

with open(f'data/{COUNTRY_CODE}_WNV_{REGION}_lau1_processed.txt', 'w', encoding=enc) as f:
    for item in attica_lau1:
        f.write("%s\n" % item)
  
print(f"Number of LAU1 Units in {REGION} (from cases): {len(attica_lau1)}")

Number of LAU1 Units in Attica (from cases): 58

In [9]:
df['period'] = df.apply(lambda row: 1 if (row['day']>=1 and row['day']<=15) else 2, axis = 1)
df['dt_placement'] = df.apply(lambda row: f"{row['year']:04}-{row['month']:02}-{1 if row['period'] == 1 else 16:02}", axis = 1)

df['dt_placement']= pd.to_datetime(df['dt_placement'])
df['case'] = 1

In [10]:
df

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,lau2,age,sex,period,dt_placement,case
0,2011-07-28,2011,7,28,αττικης,ανατολικης αττικης,μαραθωνος,μαραθωνας,25,m,2,2011-07-16,1
1,2011-07-31,2011,7,31,αττικης,ανατολικης αττικης,μαραθωνος,μαραθωνας,70,f,2,2011-07-16,1
2,2011-07-27,2011,7,27,αττικης,ανατολικης αττικης,μαραθωνος,μαραθωνας,74,m,2,2011-07-16,1
3,2011-07-27,2011,7,27,αττικης,ανατολικης αττικης,μαραθωνος,μαραθωνας,66,m,2,2011-07-16,1
4,2011-07-25,2011,7,25,αττικης,ανατολικης αττικης,σπατων-αρτεμιδος,"""αγια κυριακη σπατων"", αρτεμιδα",70,m,2,2011-07-16,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,2020-07-20,2020,7,20,αττικης,ανατολικης αττικης,μαραθωνος,σχοινιας,76,m,2,2020-07-16,1
292,2020-08-03,2020,8,3,αττικης,ανατολικης αττικης,μαραθωνος,μαραθωνας,58,m,1,2020-08-01,1
293,2021-07-23,2021,7,23,αττικης,ανατολικης αττικης,παλληνης,παλληνη,60,m,2,2021-07-16,1
294,2021-08-09,2021,8,9,αττικης,ανατολικης αττικης,σπατων-αρτεμιδος,σπατα,70,m,1,2021-08-01,1
295,2021-09-15,2021,9,15,αττικης,ανατολικης αττικης,σπατων-αρτεμιδος,αρτεμιδα,55,m,1,2021-09-01,1

In [11]:
df.drop(columns = ['onset of symptoms', 'day', 'nuts3', 'lau2', 'age', 'sex', 'period'], inplace = True)

In [12]:
df = df[['month', 'year', 'lau1', 'nuts2', 'dt_placement', 'case']]

In [13]:
df

     month  year              lau1    nuts2 dt_placement  case
0        7  2011         μαραθωνος  αττικης   2011-07-16     1
1        7  2011         μαραθωνος  αττικης   2011-07-16     1
2        7  2011         μαραθωνος  αττικης   2011-07-16     1
3        7  2011         μαραθωνος  αττικης   2011-07-16     1
4        7  2011  σπατων-αρτεμιδος  αττικης   2011-07-16     1
..     ...   ...               ...      ...          ...   ...
291      7  2020         μαραθωνος  αττικης   2020-07-16     1
292      8  2020         μαραθωνος  αττικης   2020-08-01     1
293      7  2021          παλληνης  αττικης   2021-07-16     1
294      8  2021  σπατων-αρτεμιδος  αττικης   2021-08-01     1
295      9  2021  σπατων-αρτεμιδος  αττικης   2021-09-01     1

[296 rows x 6 columns]

In [14]:
df['month'].drop_duplicates().sort_values().tolist()

[5, 6, 7, 8, 9, 10]

In [15]:
df['year'].drop_duplicates().sort_values().tolist()

[2011, 2012, 2013, 2014, 2018, 2019, 2020, 2021]

In [16]:
## Creating DataFrame to hold negative examples

df_timeline = pd.DataFrame(columns = ['lau1', 'nuts2', 'dt_placement', 'case'])

for municipality in df['lau1'].drop_duplicates().sort_values():
    for year in range(2010, 2022):
        for month in range (5,11):
            df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
            df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
            
df_timeline

C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : REGION_WNV, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_11608/2982617771.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

                lau1    nuts2 dt_placement case
0     αγιας βαρβαρας  αττικης   2010-05-01    0
1     αγιας βαρβαρας  αττικης   2010-05-16    0
2     αγιας βαρβαρας  αττικης   2010-06-01    0
3     αγιας βαρβαρας  αττικης   2010-06-16    0
4     αγιας βαρβαρας  αττικης   2010-07-01    0
...              ...      ...          ...  ...
8347          ωρωπου  αττικης   2021-08-16    0
8348          ωρωπου  αττικης   2021-09-01    0
8349          ωρωπου  αττικης   2021-09-16    0
8350          ωρωπου  αττικης   2021-10-01    0
8351          ωρωπου  αττικης   2021-10-16    0

[8352 rows x 4 columns]

In [17]:
df_timeline['dt_placement']= pd.to_datetime(df_timeline['dt_placement'])

In [18]:
df.reset_index(inplace = True, drop=True)
df_timeline.reset_index(inplace = True, drop=True)

In [19]:
## Add cases to negative examples DataFrame

#iterrate DataFrame with cases by row
for index, row in df.iterrows():
    #find index at DataFrame with negative examples where location and date matches the DataFrame with cases
    idx = df_timeline.index[(df_timeline['lau1']==row['lau1']) & (df_timeline['dt_placement']==row['dt_placement'])]
    #get the previous case number using index
    previous_case = df_timeline._get_value(idx.values[0], 'case')
    #add 1 (one) to column case
    df_timeline.at[idx.values[0],'case'] = previous_case+1

In [20]:
df_timeline['case'].value_counts().sort_index()

0     8165
1      134
2       29
3       12
4        5
5        2
6        3
9        1
11       1
Name: case, dtype: int64

In [21]:
df_timeline

                lau1    nuts2 dt_placement case
0     αγιας βαρβαρας  αττικης   2010-05-01    0
1     αγιας βαρβαρας  αττικης   2010-05-16    0
2     αγιας βαρβαρας  αττικης   2010-06-01    0
3     αγιας βαρβαρας  αττικης   2010-06-16    0
4     αγιας βαρβαρας  αττικης   2010-07-01    0
...              ...      ...          ...  ...
8347          ωρωπου  αττικης   2021-08-16    0
8348          ωρωπου  αττικης   2021-09-01    0
8349          ωρωπου  αττικης   2021-09-16    0
8350          ωρωπου  αττικης   2021-10-01    0
8351          ωρωπου  αττικης   2021-10-16    0

[8352 rows x 4 columns]

In [22]:
df_timeline.to_csv(f"data/{COUNTRY_CODE}_{REGION}_Epidemiological_Timeline_2010-2021.csv", encoding = enc, index = False)