In [1]:
import numpy as np
import pandas as pd
import random
import csv
import geopandas as gpd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, MaxAbsScaler
from sklearn.impute import KNNImputer
import sys
import pickle

sys.path.insert(0, "../../../Modules")

pd.set_option('display.max_columns', None)
random.seed(0)
np.random.seed(0)

from utils import *
from utils import process_greek

enc = 'utf-8'
shapefiles_folder = "C:/Users/dimit/Documents/noa hoard/Greece Shapefiles"

c:\Users\dimit\AppData\Local\Programs\Python\Python39\lib\site-packages\geopandas\_compat.py:112: UserWarning: The Shapely GEOS version (3.10.3-CAPI-1.16.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
NUTS0 = 'GR'
NUTS2 = 'CMacedonia'

In [4]:
YEAR = 2023
MONTH = 'June'
PERIOD = '2nd'

In [5]:
model = pickle.load(open(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_WNV_Linear_model.pkl', 'rb'))

In [6]:
data_test = read_data(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_WNV_Dataset_{YEAR}-{MONTH}-{PERIOD}.csv')
data_test.head()

,x,y,dt_placement,nuts2,lau1,day,month,week,year,day_sin,day_cos,month_sin,month_cos,week_sin,week_cos,area,population,population_density,eq_distance,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst,lst_day,lst_night,lst_jan_day_mean,lst_jan_night_mean,lst_feb_day_mean,lst_feb_night_mean,lst_mar_day_mean,lst_mar_night_mean,lst_apr_day_mean,lst_apr_night_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_jan,distance_to_coast,distance_to_river,slope_mean_1km,aspect_mean_200m,elevation_mean_1km,hillshade_mean_1km,fs_area_1km,flow_accu_200m,lc_prop1,lc_prop1_assessment,lc_prop2,lc_prop2_assessment,lc_prop3,lc_prop3_assessment,lc_type1,lc_type2,lc_type3,lc_type4,lc_type5,lw,qc,mosq_pred,mosq_previous,case
0,22.46197,40.60446,2023-06-16,κεντρικης μακεδονιας,αλεξανδρειας,16,6,24,2023,-0.101168,-0.994869,1.224647e-16,-1.0,0.292057,-0.956401,478.8,38293.0,86.8,46.40326,0.336696,0.046452,-0.328196,-0.046452,0.320650,0.046830,-0.314464,-0.046830,0.059129,0.046478,0.041888,0.046478,26.710996,35.728182,17.693810,11.510466,1.708510,11.778876,0.439805,21.186067,5.575849,24.421964,8.937268,13.120690,21.898932,139.390553,18483.883785,1629.598106,4,120.472193,7.866005,180.191380,0.0,1.400071,31,99,36,99.0,30,99,12,12,1,6,7,2,0,176,0,0
1,22.07722,41.01522,2023-06-16,κεντρικης μακεδονιας,αλμωπιας,16,6,24,2023,-0.101168,-0.994869,1.224647e-16,-1.0,0.292057,-0.956401,985.8,24924.0,28.0,46.57952,0.655554,0.261600,-0.543905,-0.261600,0.520898,0.350878,-0.422993,-0.350878,0.052447,0.032191,0.040682,0.032191,16.885166,22.562963,11.207368,9.238694,1.920162,9.573419,-0.371554,15.120878,3.834306,16.704092,6.474975,39.131645,53.565104,259.732897,25701.766035,44.089931,2,194.572797,144.613300,181.767317,0.0,113.550432,31,93,36,94.0,30,93,12,12,3,5,8,2,0,125,0,0
2,22.89198,40.65603,2023-06-16,κεντρικης μακεδονιας,αμπελοκηπων μενεμενης,16,6,24,2023,-0.101168,-0.994869,1.224647e-16,-1.0,0.292057,-0.956401,9.8,49674.0,5319.1,46.65786,0.130873,-0.012212,-0.148510,0.012212,0.160420,-0.004443,-0.176910,0.004443,0.048214,0.013890,0.044105,0.013890,NaN,32.530000,NaN,12.381429,3.596667,11.870000,2.525385,18.760769,5.121429,23.898000,11.870000,47.714562,55.270958,307.162916,1013.723139,1259.926671,2,166.963790,4.655965,180.457193,0.0,24.343007,32,97,9,99.0,30,97,13,13,10,8,9,2,0,216,0,0
3,23.95900,40.91196,2023-06-16,κεντρικης μακεδονιας,αμφιπολης,16,6,24,2023,-0.101168,-0.994869,1.224647e-16,-1.0,0.292057,-0.956401,411.8,7169.0,22.3,47.41120,0.515208,0.213381,-0.439958,-0.213381,0.403006,0.237790,-0.342732,-0.237790,0.027605,0.030547,0.021885,0.030547,21.111333,26.166000,16.056667,10.655161,3.113550,9.895287,0.416503,16.682835,4.861432,20.539981,7.233860,5.649901,7.017309,119.417271,14413.246350,196.335052,5,220.810138,250.710581,185.823044,0.0,25.464784,31,88,30,88.0,30,88,10,10,1,6,6,2,0,149,0,0
4,23.69747,40.49593,2023-06-16,κεντρικης μακεδονιας,αριστοτελη,16,6,24,2023,-0.101168,-0.994869,1.224647e-16,-1.0,0.292057,-0.956401,747.0,16994.0,24.5,46.92004,0.654915,0.349892,-0.544854,-0.349892,0.638839,0.340437,-0.531059,-0.340437,0.033780,0.025713,0.026395,0.025713,18.539135,22.370556,14.707714,10.968774,3.770478,9.453781,2.661346,15.362634,4.844974,17.259672,7.381085,23.168873,26.074137,262.277332,11468.297401,1749.385768,22,273.587292,768.043224,181.562024,0.0,1.033661,14,99,10,99.0,10,99,4,4,6,4,4,2,0,97,0,0

In [7]:
X_test = data_test.select_dtypes(exclude=['object']).drop(columns = ['case'])
y_test = data_test['case']

scaler = MinMaxScaler()
imputer = KNNImputer()

X_test = scaler.fit_transform(X_test)
X_test = imputer.fit_transform(X_test)

results_test = inference_lin_model(model, data_test, X_test, y_test)

In [8]:
results_test.drop(columns='case', inplace= True)
results_test

           x         y                   lau1  day  month  year     score
0   22.90326  40.67609      κορδελιου ευοσμου   16      6  2023  0.996138
1   22.91743  40.42897              θερμαϊκου   16      6  2023  0.978529
2   22.89198  40.65603  αμπελοκηπων μενεμενης   16      6  2023  0.954076
3   23.46965  40.01303             κασσανδρας   16      6  2023  0.946458
4   22.95369  40.62334           θεσσαλονικης   16      6  2023  0.930790
5   23.19403  40.32484       νεας προποντιδας   16      6  2023  0.926467
6   22.37828  40.28551              κατερινης   16      6  2023  0.909869
7   22.72632  40.61725                  δελτα   16      6  2023  0.898748
8   23.07188  40.61371       πυλαιας χορτιατη   16      6  2023  0.897291
9   23.08410  40.49006                 θερμης   16      6  2023  0.895642
10  22.19377  40.47808                βεροιας   16      6  2023  0.889015
11  23.27201  41.13057              ηρακλειας   16      6  2023  0.888946
12  23.87955  40.08302               σιθωνιας   16      6  2023  0.868183
13  22.95724  40.57876             καλαμαριας   16      6  2023  0.842456
14  23.57073  40.89405              βισαλτιας   16      6  2023  0.817609
15  22.17237  40.79674                σκυδρας   16      6  2023  0.812164
16  23.42474  40.40349              πολυγυρου   16      6  2023  0.811277
17  23.67524  41.04497        εμμανουηλ παππα   16      6  2023  0.810617
18  22.95341  40.68195            παυλου μελα   16      6  2023  0.810131
19  23.95900  40.91196              αμφιπολης   16      6  2023  0.800176
20  23.49303  40.69079                 βολβης   16      6  2023  0.780775
21  23.55132  41.12829                 σερρων   16      6  2023  0.714020
22  22.46197  40.60446           αλεξανδρειας   16      6  2023  0.708125
23  22.07722  41.01522               αλμωπιας   16      6  2023  0.678986
24  22.90397  41.04735                 κιλκις   16      6  2023  0.660251
25  22.90881  40.77096           ωραιοκαστρου   16      6  2023  0.649881
26  22.36451  40.79600                 πελλας   16      6  2023  0.633635
27  23.28798  41.28841               σιντικης   16      6  2023  0.622484
28  23.85648  41.01727            νεας ζιχνης   16      6  2023  0.583021
29  23.69747  40.49593             αριστοτελη   16      6  2023  0.555563
30  22.65595  40.73784             χαλκηδονος   16      6  2023  0.535492
31  22.51017  40.99009               παιονιας   16      6  2023  0.511400
32  23.19199  40.78993                λαγκαδα   16      6  2023  0.499187
33  22.52772  40.45904       πυδνας κολινδρου   16      6  2023  0.439458
34  22.97547  40.65206        νεαπολης συκεων   16      6  2023  0.431963
35  21.93869  40.79699                εδεσσας   16      6  2023  0.392736
36  22.47539  40.12020           διου ολυμπου   16      6  2023  0.343040
37  22.04734  40.63497                ναουσας   16      6  2023  0.150065

In [9]:
bins_path = f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Bins_{YEAR}.csv'

bins = []

with open(bins_path, mode='r', newline='') as file:
    reader = csv.reader(file)
    for row in reader:
        bins.extend(map(float, row))

print(bins)

[0.0, 0.0648252687608289, 0.3787123377107355, 0.6803072708219687, 0.838221147727126, 0.935474790938512, 1.0]

In [10]:
results_test['risk_class'] = pd.cut(results_test['score'], bins=bins, labels=False, include_lowest=True)
results_test

,x,y,lau1,day,month,year,score,risk_class
0,22.90326,40.67609,κορδελιου ευοσμου,16,6,2023,0.996138,5
1,22.91743,40.42897,θερμαϊκου,16,6,2023,0.978529,5
2,22.89198,40.65603,αμπελοκηπων μενεμενης,16,6,2023,0.954076,5
3,23.46965,40.01303,κασσανδρας,16,6,2023,0.946458,5
4,22.95369,40.62334,θεσσαλονικης,16,6,2023,0.930790,4
5,23.19403,40.32484,νεας προποντιδας,16,6,2023,0.926467,4
6,22.37828,40.28551,κατερινης,16,6,2023,0.909869,4
7,22.72632,40.61725,δελτα,16,6,2023,0.898748,4
8,23.07188,40.61371,πυλαιας χορτιατη,16,6,2023,0.897291,4
9,23.08410,40.49006,θερμης,16,6,2023,0.895642,4
10,22.19377,40.47808,βεροιας,16,6,2023,0.889015,4
11,23.27201,41.13057,ηρακλειας,16,6,2023,0.888946,4
12,23.87955,40.08302,σιθωνιας,16,6,2023,0.868183,4
13,22.95724,40.57876,καλαμαριας,16,6,2023,0.842456,4
14,23.57073,40.89405,βισαλτιας,16,6,2023,0.817609,3
15,22.17237,40.79674,σκυδρας,16,6,2023,0.812164,3
16,23.42474,40.40349,πολυγυρου,16,6,2023,0.811277,3
17,23.67524,41.04497,εμμανουηλ παππα,16,6,2023,0.810617,3
18,22.95341,40.68195,παυλου μελα,16,6,2023,0.810131,3
19,23.95900,40.91196,αμφιπολης,16,6,2023,0.800176,3
20,23.49303,40.69079,βολβης,16,6,2023,0.780775,3
21,23.55132,41.12829,σερρων,16,6,2023,0.714020,3
22,22.46197,40.60446,αλεξανδρειας,16,6,2023,0.708125,3
23,22.07722,41.01522,αλμωπιας,16,6,2023,0.678986,2
24,22.90397,41.04735,κιλκις,16,6,2023,0.660251,2
25,22.90881,40.77096,ωραιοκαστρου,16,6,2023,0.649881,2
26,22.36451,40.79600,πελλας,16,6,2023,0.633635,2
27,23.28798,41.28841,σιντικης,16,6,2023,0.622484,2
28,23.85648,41.01727,νεας ζιχνης,16,6,2023,0.583021,2
29,23.69747,40.49593,αριστοτελη,16,6,2023,0.555563,2
30,22.65595,40.73784,χαλκηδονος,16,6,2023,0.535492,2
31,22.51017,40.99009,παιονιας,16,6,2023,0.511400,2
32,23.19199,40.78993,λαγκαδα,16,6,2023,0.499187,2
33,22.52772,40.45904,πυδνας κολινδρου,16,6,2023,0.439458,2
34,22.97547,40.65206,νεαπολης συκεων,16,6,2023,0.431963,2
35,21.93869,40.79699,εδεσσας,16,6,2023,0.392736,2
36,22.47539,40.12020,διου ολυμπου,16,6,2023,0.343040,1
37,22.04734,40.63497,ναουσας,16,6,2023,0.150065,1

In [11]:
results_test.to_csv(f"../../data/{NUTS2}/results/{NUTS0}_{NUTS2}_Results_{YEAR}-{MONTH}-{PERIOD}_(new).csv", encoding = enc, index = False)

In [12]:
##TODO Visualisation of results