In [1]:
import numpy as np
import pandas as pd
import random
import csv
import geopandas as gpd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, MaxAbsScaler
from sklearn.impute import KNNImputer
import sys
import pickle

sys.path.insert(0, "../../../Modules")

pd.set_option('display.max_columns', None)
random.seed(0)
np.random.seed(0)

from utils import *
from utils import process_greek

enc = 'utf-8'
shapefiles_folder = "C:/Users/dimit/Documents/noa hoard/Greece Shapefiles"

c:\Users\dimit\AppData\Local\Programs\Python\Python39\lib\site-packages\geopandas\_compat.py:112: UserWarning: The Shapely GEOS version (3.10.3-CAPI-1.16.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
NUTS0 = 'GR'
NUTS2 = 'CMacedonia'

In [4]:
YEAR = 2023
MONTH = 'July'
PERIOD = '1st'

In [5]:
model = pickle.load(open(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_WNV_Linear_model.pkl', 'rb'))

In [6]:
data_test = read_data(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_WNV_Dataset_{YEAR}-{MONTH}-{PERIOD}.csv')
data_test.head()

,x,y,dt_placement,nuts2,lau1,day,month,week,year,day_sin,day_cos,month_sin,month_cos,week_sin,week_cos,area,population,population_density,eq_distance,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst,lst_day,lst_night,lst_jan_day_mean,lst_jan_night_mean,lst_feb_day_mean,lst_feb_night_mean,lst_mar_day_mean,lst_mar_night_mean,lst_apr_day_mean,lst_apr_night_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_jan,distance_to_coast,distance_to_river,slope_mean_1km,aspect_mean_200m,elevation_mean_1km,hillshade_mean_1km,fs_area_1km,flow_accu_200m,lc_prop1,lc_prop1_assessment,lc_prop2,lc_prop2_assessment,lc_prop3,lc_prop3_assessment,lc_type1,lc_type2,lc_type3,lc_type4,lc_type5,lw,qc,mosq_pred,mosq_previous,case
0,22.46197,40.60446,2023-07-01,κεντρικης μακεδονιας,αλεξανδρειας,1,7,26,2023,0.201299,0.97953,-0.5,-0.866025,0.059241,-0.998244,478.8,38293.0,86.8,46.40326,0.443633,0.091123,-0.410712,-0.091123,0.436110,0.083677,-0.406568,-0.083677,0.065233,0.056808,0.046135,0.056808,26.303636,33.969091,18.638182,11.510466,1.708510,11.778876,0.439805,21.186067,5.575849,24.421964,8.937268,0.019684,12.731238,162.319735,18483.883785,1629.598106,4,120.472193,7.866005,180.191380,0.0,1.400071,31,99,36,99.0,30,99,12,12,1,6,7,2,0,98,0,0
1,22.07722,41.01522,2023-07-01,κεντρικης μακεδονιας,αλμωπιας,1,7,26,2023,0.201299,0.97953,-0.5,-0.866025,0.059241,-0.998244,985.8,24924.0,28.0,46.57952,0.637817,0.219933,-0.532816,-0.219933,0.641268,0.225652,-0.535202,-0.225652,0.049041,0.039089,0.037401,0.039089,20.496111,25.263704,15.728519,9.238694,1.920162,9.573419,-0.371554,15.120878,3.834306,16.704092,6.474975,4.350408,11.247896,272.297521,25701.766035,44.089931,2,194.572797,144.613300,181.767317,0.0,113.550432,31,93,36,94.0,30,93,12,12,3,5,8,2,0,125,0,0
2,22.89198,40.65603,2023-07-01,κεντρικης μακεδονιας,αμπελοκηπων μενεμενης,1,7,26,2023,0.201299,0.97953,-0.5,-0.866025,0.059241,-0.998244,9.8,49674.0,5319.1,46.65786,0.133415,-0.028332,-0.154901,0.028332,0.178877,-0.018693,-0.194543,0.018693,0.064165,0.025060,0.052170,0.025060,29.670000,35.870000,23.470000,12.381429,3.596667,11.870000,2.525385,18.760769,5.121429,23.898000,11.870000,0.152377,14.319245,388.329452,1013.723139,1259.926671,2,166.963790,4.655965,180.457193,0.0,24.343007,32,97,9,99.0,30,97,13,13,10,8,9,2,0,168,0,0
3,23.95900,40.91196,2023-07-01,κεντρικης μακεδονιας,αμφιπολης,1,7,26,2023,0.201299,0.97953,-0.5,-0.866025,0.059241,-0.998244,411.8,7169.0,22.3,47.41120,0.465554,0.152817,-0.409653,-0.152817,0.476908,0.163920,-0.414256,-0.163920,0.086002,0.067399,0.065623,0.067399,24.638000,30.062000,19.214000,10.655161,3.113550,9.895287,0.416503,16.682835,4.861432,20.539981,7.233860,0.089718,2.288451,126.572897,14413.246350,196.335052,5,220.810138,250.710581,185.823044,0.0,25.464784,31,88,30,88.0,30,88,10,10,1,6,6,2,0,119,0,0
4,23.69747,40.49593,2023-07-01,κεντρικης μακεδονιας,αριστοτελη,1,7,26,2023,0.201299,0.97953,-0.5,-0.866025,0.059241,-0.998244,747.0,16994.0,24.5,46.92004,0.624553,0.337493,-0.503456,-0.337493,0.606419,0.316767,-0.497883,-0.316767,0.071280,0.048828,0.062302,0.048828,21.445833,24.884444,18.007222,10.968774,3.770478,9.453781,2.661346,15.362634,4.844974,17.259672,7.381085,0.820154,2.131676,336.645283,11468.297401,1749.385768,22,273.587292,768.043224,181.562024,0.0,1.033661,14,99,10,99.0,10,99,4,4,6,4,4,2,0,80,0,0

In [7]:
X_test = data_test.select_dtypes(exclude=['object']).drop(columns = ['case'])
y_test = data_test['case']

scaler = MinMaxScaler()
imputer = KNNImputer()

X_test = scaler.fit_transform(X_test)
X_test = imputer.fit_transform(X_test)

results_test = inference_lin_model(model, data_test, X_test, y_test)

In [8]:
results_test.drop(columns='case', inplace= True)
results_test

           x         y                   lau1  day  month  year     score
0   22.90326  40.67609      κορδελιου ευοσμου    1      7  2023  0.997925
1   22.95369  40.62334           θεσσαλονικης    1      7  2023  0.995605
2   22.89198  40.65603  αμπελοκηπων μενεμενης    1      7  2023  0.993014
3   22.91743  40.42897              θερμαϊκου    1      7  2023  0.989822
4   22.95341  40.68195            παυλου μελα    1      7  2023  0.987118
5   22.95724  40.57876             καλαμαριας    1      7  2023  0.985124
6   23.27201  41.13057              ηρακλειας    1      7  2023  0.956962
7   22.72632  40.61725                  δελτα    1      7  2023  0.956428
8   23.19403  40.32484       νεας προποντιδας    1      7  2023  0.955399
9   23.08410  40.49006                 θερμης    1      7  2023  0.946592
10  23.28798  41.28841               σιντικης    1      7  2023  0.936733
11  23.55132  41.12829                 σερρων    1      7  2023  0.926266
12  22.37828  40.28551              κατερινης    1      7  2023  0.908946
13  23.46965  40.01303             κασσανδρας    1      7  2023  0.898983
14  23.57073  40.89405              βισαλτιας    1      7  2023  0.897139
15  23.42474  40.40349              πολυγυρου    1      7  2023  0.879453
16  22.65595  40.73784             χαλκηδονος    1      7  2023  0.874105
17  23.87955  40.08302               σιθωνιας    1      7  2023  0.853742
18  22.19377  40.47808                βεροιας    1      7  2023  0.847987
19  23.67524  41.04497        εμμανουηλ παππα    1      7  2023  0.844213
20  23.07188  40.61371       πυλαιας χορτιατη    1      7  2023  0.834811
21  22.97547  40.65206        νεαπολης συκεων    1      7  2023  0.829358
22  22.46197  40.60446           αλεξανδρειας    1      7  2023  0.778126
23  22.90397  41.04735                 κιλκις    1      7  2023  0.739040
24  22.90881  40.77096           ωραιοκαστρου    1      7  2023  0.736848
25  22.17237  40.79674                σκυδρας    1      7  2023  0.730640
26  23.49303  40.69079                 βολβης    1      7  2023  0.713961
27  23.95900  40.91196              αμφιπολης    1      7  2023  0.664960
28  23.85648  41.01727            νεας ζιχνης    1      7  2023  0.639322
29  22.36451  40.79600                 πελλας    1      7  2023  0.636733
30  23.69747  40.49593             αριστοτελη    1      7  2023  0.636597
31  23.19199  40.78993                λαγκαδα    1      7  2023  0.617540
32  22.51017  40.99009               παιονιας    1      7  2023  0.494321
33  22.04734  40.63497                ναουσας    1      7  2023  0.375366
34  22.52772  40.45904       πυδνας κολινδρου    1      7  2023  0.278919
35  22.07722  41.01522               αλμωπιας    1      7  2023  0.261124
36  21.93869  40.79699                εδεσσας    1      7  2023  0.239593
37  22.47539  40.12020           διου ολυμπου    1      7  2023  0.192490

In [9]:
bins_path = f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Bins_{YEAR}.csv'

bins = []

with open(bins_path, mode='r', newline='') as file:
    reader = csv.reader(file)
    for row in reader:
        bins.extend(map(float, row))

print(bins)

[0.0, 0.0648252687608289, 0.3787123377107355, 0.6803072708219687, 0.838221147727126, 0.935474790938512, 1.0]

In [10]:
results_test['risk_class'] = pd.cut(results_test['score'], bins=bins, labels=False, include_lowest=True)
results_test

,x,y,lau1,day,month,year,score,risk_class
0,22.90326,40.67609,κορδελιου ευοσμου,1,7,2023,0.997925,5
1,22.95369,40.62334,θεσσαλονικης,1,7,2023,0.995605,5
2,22.89198,40.65603,αμπελοκηπων μενεμενης,1,7,2023,0.993014,5
3,22.91743,40.42897,θερμαϊκου,1,7,2023,0.989822,5
4,22.95341,40.68195,παυλου μελα,1,7,2023,0.987118,5
5,22.95724,40.57876,καλαμαριας,1,7,2023,0.985124,5
6,23.27201,41.13057,ηρακλειας,1,7,2023,0.956962,5
7,22.72632,40.61725,δελτα,1,7,2023,0.956428,5
8,23.19403,40.32484,νεας προποντιδας,1,7,2023,0.955399,5
9,23.08410,40.49006,θερμης,1,7,2023,0.946592,5
10,23.28798,41.28841,σιντικης,1,7,2023,0.936733,5
11,23.55132,41.12829,σερρων,1,7,2023,0.926266,4
12,22.37828,40.28551,κατερινης,1,7,2023,0.908946,4
13,23.46965,40.01303,κασσανδρας,1,7,2023,0.898983,4
14,23.57073,40.89405,βισαλτιας,1,7,2023,0.897139,4
15,23.42474,40.40349,πολυγυρου,1,7,2023,0.879453,4
16,22.65595,40.73784,χαλκηδονος,1,7,2023,0.874105,4
17,23.87955,40.08302,σιθωνιας,1,7,2023,0.853742,4
18,22.19377,40.47808,βεροιας,1,7,2023,0.847987,4
19,23.67524,41.04497,εμμανουηλ παππα,1,7,2023,0.844213,4
20,23.07188,40.61371,πυλαιας χορτιατη,1,7,2023,0.834811,3
21,22.97547,40.65206,νεαπολης συκεων,1,7,2023,0.829358,3
22,22.46197,40.60446,αλεξανδρειας,1,7,2023,0.778126,3
23,22.90397,41.04735,κιλκις,1,7,2023,0.739040,3
24,22.90881,40.77096,ωραιοκαστρου,1,7,2023,0.736848,3
25,22.17237,40.79674,σκυδρας,1,7,2023,0.730640,3
26,23.49303,40.69079,βολβης,1,7,2023,0.713961,3
27,23.95900,40.91196,αμφιπολης,1,7,2023,0.664960,2
28,23.85648,41.01727,νεας ζιχνης,1,7,2023,0.639322,2
29,22.36451,40.79600,πελλας,1,7,2023,0.636733,2
30,23.69747,40.49593,αριστοτελη,1,7,2023,0.636597,2
31,23.19199,40.78993,λαγκαδα,1,7,2023,0.617540,2
32,22.51017,40.99009,παιονιας,1,7,2023,0.494321,2
33,22.04734,40.63497,ναουσας,1,7,2023,0.375366,1
34,22.52772,40.45904,πυδνας κολινδρου,1,7,2023,0.278919,1
35,22.07722,41.01522,αλμωπιας,1,7,2023,0.261124,1
36,21.93869,40.79699,εδεσσας,1,7,2023,0.239593,1
37,22.47539,40.12020,διου ολυμπου,1,7,2023,0.192490,1

In [11]:
results_test.to_csv(f"../../data/{NUTS2}/results/{NUTS0}_{NUTS2}_Results_{YEAR}-{MONTH}-{PERIOD}_(new).csv", encoding = enc, index = False)

In [12]:
##TODO Visualisation of results