## Creates the **Epidemiological Timeline** for a specific region by using the available data on WNV Cases ##

In [1]:
import pandas as pd

enc = 'utf-8'
dec = 'greek8'

pd.options.display.max_columns = None
pd.options.display.max_rows = 10

In [2]:
NUTS0 = 'GR'
NUTS2 = 'Thessaly'
NUTS2_EL = 'θεσσαλιας'

In [3]:
data = pd.read_csv(f'../../data/{NUTS0}_WNV_cases_2022_processed.csv', encoding = enc)
data.head(5)

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,cases
0,2022-07-12,2022,7,12,κεντρικης μακεδονιας,θεσσαλονικης,αμπελοκηπων μενεμενης,1
1,2022-07-19,2022,7,19,κεντρικης μακεδονιας,θεσσαλονικης,δελτα,2
2,2022-07-19,2022,7,19,κεντρικης μακεδονιας,θεσσαλονικης,χαλκηδονος,1
3,2022-07-16,2022,7,16,κεντρικης μακεδονιας,θεσσαλονικης,δελτα,1
4,2022-07-16,2022,7,16,κεντρικης μακεδονιας,θεσσαλονικης,θερμης,1

In [4]:
data.shape

(177, 8)

In [5]:
df = data[data['nuts2'].isin([NUTS2_EL])].copy()

In [6]:
df.reset_index(drop = True, inplace = True)

In [7]:
df

   onset of symptoms  year  month  day      nuts2     nuts3        lau1  cases
0         2022-07-16  2022      7   16  θεσσαλιας   λαρισας      τεμπων      1
1         2022-08-16  2022      8   16  θεσσαλιας  τρικαλων  φαρκαδονας      1
2         2022-08-23  2022      8   23  θεσσαλιας   λαρισας   λαρισαιων      3
3         2022-08-23  2022      8   23  θεσσαλιας  τρικαλων  φαρκαδονας      1
4         2022-08-30  2022      8   30  θεσσαλιας   λαρισας   λαρισαιων      1
..               ...   ...    ...  ...        ...       ...         ...    ...
17        2022-10-04  2022     10    4  θεσσαλιας   λαρισας   λαρισαιων      2
18        2022-10-04  2022     10    4  θεσσαλιας   λαρισας     κιλελερ      1
19        2022-10-04  2022     10    4  θεσσαλιας   λαρισας    φαρσαλων      1
20        2022-10-11  2022     10   11  θεσσαλιας   λαρισας   λαρισαιων      2
21        2022-10-18  2022     10   18  θεσσαλιας   λαρισας   λαρισαιων      1

[22 rows x 8 columns]

In [8]:
wnv_lau1_list = df['lau1'].drop_duplicates().sort_values().tolist()

with open(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_WNV_2022_LAU1_Units_Processed.txt', 'w', encoding=enc) as f:
    for item in wnv_lau1_list:
        f.write("%s\n" % item)
  
print(f"Number of LAU1 Units in {NUTS2} (from cases): {len(wnv_lau1_list)}")

Number of LAU1 Units in Thessaly (from cases): 6

In [9]:
df['period'] = df.apply(lambda row: 1 if (row['day']>=1 and row['day']<=15) else 2, axis = 1)
df['dt_placement'] = df.apply(lambda row: f"{row['year']:04}-{row['month']:02}-{1 if row['period'] == 1 else 16:02}", axis = 1)

df['dt_placement']= pd.to_datetime(df['dt_placement'])

In [10]:
df

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,cases,period,dt_placement
0,2022-07-16,2022,7,16,θεσσαλιας,λαρισας,τεμπων,1,2,2022-07-16
1,2022-08-16,2022,8,16,θεσσαλιας,τρικαλων,φαρκαδονας,1,2,2022-08-16
2,2022-08-23,2022,8,23,θεσσαλιας,λαρισας,λαρισαιων,3,2,2022-08-16
3,2022-08-23,2022,8,23,θεσσαλιας,τρικαλων,φαρκαδονας,1,2,2022-08-16
4,2022-08-30,2022,8,30,θεσσαλιας,λαρισας,λαρισαιων,1,2,2022-08-16
...,...,...,...,...,...,...,...,...,...,...
17,2022-10-04,2022,10,4,θεσσαλιας,λαρισας,λαρισαιων,2,1,2022-10-01
18,2022-10-04,2022,10,4,θεσσαλιας,λαρισας,κιλελερ,1,1,2022-10-01
19,2022-10-04,2022,10,4,θεσσαλιας,λαρισας,φαρσαλων,1,1,2022-10-01
20,2022-10-11,2022,10,11,θεσσαλιας,λαρισας,λαρισαιων,2,1,2022-10-01
21,2022-10-18,2022,10,18,θεσσαλιας,λαρισας,λαρισαιων,1,2,2022-10-16

In [11]:
df.drop(columns = ['onset of symptoms', 'day', 'nuts3', 'period'], inplace = True)

In [12]:
df = df[['month', 'year', 'lau1', 'nuts2', 'dt_placement', 'cases']]

In [13]:
df

    month  year        lau1      nuts2 dt_placement  cases
0       7  2022      τεμπων  θεσσαλιας   2022-07-16      1
1       8  2022  φαρκαδονας  θεσσαλιας   2022-08-16      1
2       8  2022   λαρισαιων  θεσσαλιας   2022-08-16      3
3       8  2022  φαρκαδονας  θεσσαλιας   2022-08-16      1
4       8  2022   λαρισαιων  θεσσαλιας   2022-08-16      1
..    ...   ...         ...        ...          ...    ...
17     10  2022   λαρισαιων  θεσσαλιας   2022-10-01      2
18     10  2022     κιλελερ  θεσσαλιας   2022-10-01      1
19     10  2022    φαρσαλων  θεσσαλιας   2022-10-01      1
20     10  2022   λαρισαιων  θεσσαλιας   2022-10-01      2
21     10  2022   λαρισαιων  θεσσαλιας   2022-10-16      1

[22 rows x 6 columns]

In [14]:
case_months = df['month'].drop_duplicates().sort_values().tolist()
case_months

[7, 8, 9, 10]

In [15]:
case_years = df['year'].drop_duplicates().sort_values().tolist()
case_years

[2022]

In [16]:
with open(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_WNV_2022_Cases_Dates.txt', 'w', encoding=enc) as f:

    f.write("%s: " % 'months')
    for item in case_months:
        f.write("%s, " % item)

    f.write("\n")

    f.write("%s: " % 'years')
    for item in case_years:
        f.write("%s, " % item)

In [17]:
## Creating DataFrame to hold negative examples

df_timeline = pd.DataFrame(columns = ['lau1', 'nuts2', 'dt_placement', 'case'])

for municipality in df['lau1'].drop_duplicates().sort_values():
    for month in range (7,12):
        df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
        df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
            
df_timeline

C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
C:\Users\dimit\AppData\Local\Temp/ipykernel_19160/3484021064.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{2022:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)

        lau1      nuts2 dt_placement case
0    κιλελερ  θεσσαλιας   2022-07-01    0
1    κιλελερ  θεσσαλιας   2022-07-16    0
2    κιλελερ  θεσσαλιας   2022-08-01    0
3    κιλελερ  θεσσαλιας   2022-08-16    0
4    κιλελερ  θεσσαλιας   2022-09-01    0
..       ...        ...          ...  ...
55  φαρσαλων  θεσσαλιας   2022-09-16    0
56  φαρσαλων  θεσσαλιας   2022-10-01    0
57  φαρσαλων  θεσσαλιας   2022-10-16    0
58  φαρσαλων  θεσσαλιας   2022-11-01    0
59  φαρσαλων  θεσσαλιας   2022-11-16    0

[60 rows x 4 columns]

In [18]:
df_timeline['dt_placement']= pd.to_datetime(df_timeline['dt_placement'])

In [19]:
df.reset_index(inplace = True, drop=True)
df_timeline.reset_index(inplace = True, drop=True)

In [20]:
## Add cases to negative examples DataFrame

#iterrate DataFrame with cases by row
for index, row in df.iterrows():
    #find index at DataFrame with negative examples where location and date matches the DataFrame with cases
    idx = df_timeline.index[(df_timeline['lau1']==row['lau1']) & (df_timeline['dt_placement']==row['dt_placement'])]
    #get the previous case number using index
    previous_case = df_timeline._get_value(idx.values[0], 'case')
    #add 1 (one) to column case
    df_timeline.at[idx.values[0],'case'] = previous_case+1

In [21]:
df_timeline['case'].value_counts().sort_index()

0    45
1     8
2     7
Name: case, dtype: int64

In [22]:
df_timeline

        lau1      nuts2 dt_placement case
0    κιλελερ  θεσσαλιας   2022-07-01    0
1    κιλελερ  θεσσαλιας   2022-07-16    0
2    κιλελερ  θεσσαλιας   2022-08-01    0
3    κιλελερ  θεσσαλιας   2022-08-16    1
4    κιλελερ  θεσσαλιας   2022-09-01    0
..       ...        ...          ...  ...
55  φαρσαλων  θεσσαλιας   2022-09-16    0
56  φαρσαλων  θεσσαλιας   2022-10-01    1
57  φαρσαλων  θεσσαλιας   2022-10-16    0
58  φαρσαλων  θεσσαλιας   2022-11-01    0
59  φαρσαλων  θεσσαλιας   2022-11-16    0

[60 rows x 4 columns]

In [23]:
df_timeline.case.sum()

22

In [24]:
df_timeline.to_csv(f"../../data/{NUTS2}/{NUTS0}_{NUTS2}_WNV_Cases_2022.csv", encoding = enc, index = False)